// Copyright (C) 2015-2026 The Neo Project.
//
// Contract.cs file belongs to the neo project and is free
// software distributed under the MIT software license, see the
// accompanying file LICENSE in the main directory of the
// repository or http://www.opensource.org/licenses/mit-license.php
// for more details.
//
// Redistribution and use in source and binary forms with or without
// modifications are permitted.

using Neo.SmartContract.Framework.Attributes;

namespace Neo.SmartContract.Framework.Services
{
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
    public class Contract
    {
        /// <summary>
        /// Id. It generated by the system when the contract is deployed.
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// UpdateCounter. It is used to track the number of updates to the contract.
        /// </summary>
        public readonly ushort UpdateCounter;

        /// <summary>
        /// Hash. It is the hash of the contract and generated when the first deployment.
        /// </summary>
        public readonly UInt160 Hash;

        /// <summary>
        /// Nef. It is the NEF file(i.e. the compiled contract) of the contract.
        /// </summary>
        public readonly ByteString Nef;

        /// <summary>
        /// Manifest. It is the manifest of the contract.
        /// </summary>
        public readonly ContractManifest Manifest;

        /// <summary>
        /// Calls the contract with the specified method, callflags and arguments.
        /// <para>
        /// The execution will fail if:
        /// 1. The 'scriptHash', or 'method' is null.
        /// 2. The 'flags' is not a valid <see cref="CallFlags"/>.
        /// 3. The contract or method does not exist.
        /// 4. The contract is blocked.
        /// 5. The arguments.Length is not equal to the parameter count of the method.
        /// 6. The method is not safe and the contract method is not allowed to be called by the current context.
        /// </para>
        /// </summary>
        [Syscall("System.Contract.Call")]
        public static extern object Call(UInt160 scriptHash, string method, CallFlags flags, params object?[]? args);

        /// <summary>
        /// Gets the <see cref="CallFlags"/> of the current context.
        /// </summary>
        [Syscall("System.Contract.GetCallFlags")]
        public static extern CallFlags GetCallFlags();

        /// <summary>
        /// Gets the corresponding account scripthash for the given public key.
        /// <para>
        /// The execution will fail if the pubkey is null.
        /// </para>
        /// </summary>
        [Syscall("System.Contract.CreateStandardAccount")]
        public static extern UInt160 CreateStandardAccount(ECPoint pubKey);

        /// <summary>
        /// Gets the corresponding multisig account scripthash for the given public keys.
        /// <para>
        /// The execution will fail if:
        /// 1. The pubkeys is null.
        /// 2. The 'm' is less than 1 or greater than 1024 or m greater than pubkeys.Length.
        /// </para>
        /// </summary>
        [Syscall("System.Contract.CreateMultisigAccount")]
        public static extern UInt160 CreateMultisigAccount(int m, params ECPoint[] pubKey);
    }
#pragma warning restore CS8618
}
