blank_issues_enabled: false
contact_links:
  - name: NEO Discord Community
    url: https://discord.gg/rvZFQ5382k
    about: Join our Discord for general questions and community discussions
  - name: NEO Documentation
    url: https://docs.neo.org/
    about: Check the official NEO documentation for guides and references
  - name: Security Issues
    url: https://github.com/neo-project/neo-devpack-dotnet/security/advisories/new
    about: Report security vulnerabilities privately through GitHub Security Advisories