using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;

namespace Neo.BuildTasks
{
    public static class ContractGenerator
    {
        // generated from Roslyn C# 4.1 SyntaxFacts.GetKeywordKinds().Select(k => SyntaxFacts.GetText(k)).OrderBy(k => k)
        static readonly ImmutableHashSet<string> CSHARP_KEYWORDS = ImmutableHashSet.Create("__arglist", "__makeref",
            "__reftype", "__refvalue", "abstract", "add", "alias", "and", "as", "ascending", "assembly", "async",
            "await", "base", "bool", "break", "by", "byte", "case", "catch", "char", "checked", "class", "const",
            "continue", "decimal", "default", "delegate", "descending", "do", "double", "else", "enum", "equals",
            "event", "explicit", "extern", "false", "field", "finally", "fixed", "float", "for", "foreach", "from",
            "get", "global", "goto", "group", "if", "implicit", "in", "init", "int", "interface", "internal", "into",
            "is", "join", "let", "lock", "long", "managed", "method", "module", "nameof", "namespace", "new", "not",
            "null", "object", "on", "operator", "or", "orderby", "out", "override", "param", "params", "partial",
            "private", "property", "protected", "public", "readonly", "record", "ref", "remove", "return", "sbyte",
            "sealed", "select", "set", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
            "throw", "true", "try", "type", "typeof", "typevar", "uint", "ulong", "unchecked", "unmanaged", "unsafe",
            "ushort", "using", "virtual", "void", "volatile", "when", "where", "while", "with", "yield");

        public static string GenerateContractInterface(NeoManifest manifest, string @namespace = "")
        {
            var contractName = Regex.Replace(manifest.Name, "^.*\\.", string.Empty);

            var builder = new IndentedStringBuilder();

            builder.AppendLines($@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

");

            if (@namespace.Length > 0)
            {
                builder.AppendLine($"namespace {@namespace} {{");
                builder.IncrementIndent();
            }
            builder.AppendLines($@"#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode(""Neo.BuildTasks"",""{ThisAssembly.AssemblyFileVersion}"")]
#endif
");
            builder.AppendLine($"[System.ComponentModel.Description(\"{manifest.Name}\")]");

            builder.AppendLine($"interface {contractName} {{");
            builder.IncrementIndent();
            for (int i = 0; i < manifest.Methods.Count; i++)
            {
                var method = manifest.Methods[i];
                if (method.Name.StartsWith("_")) continue;

                builder.Append($"{ConvertParameterType(method.ReturnType)} {method.Name}(");
                builder.Append(string.Join(", ", method.Parameters.Select(p => $"{ConvertParameterType(p.Type)} {ConvertIdentifier(p.Name)}")));
                builder.AppendLine(");");
            }

            if (manifest.Events.Count > 0)
            {
                builder.AppendLine("interface Events {");
                builder.IncrementIndent();
                for (int i = 0; i < manifest.Events.Count; i++)
                {
                    var @event = manifest.Events[i];
                    builder.Append($"void {@event.Name}(");
                    builder.Append(string.Join(", ", @event.Parameters.Select(p => $"{ConvertParameterType(p.Type)} {ConvertIdentifier(p.Name)}")));
                    builder.AppendLine($");");
                }
                builder.DecrementIndent();
                builder.AppendLine("}");
            }

            builder.DecrementIndent();
            builder.AppendLine("}");

            if (@namespace.Length > 0)
            {
                builder.DecrementIndent();
                builder.AppendLine("}");
            }

            return builder.ToString();

            static string ConvertIdentifier(string text) => CSHARP_KEYWORDS.Contains(text) ? $"@{text}" : text;

            static string ConvertParameterType(string parameterType) => parameterType switch
            {
                "Any" => "object",
                "Array" => "Neo.VM.Types.Array",
                "Boolean" => "bool",
                "ByteArray" => "byte[]",
                "Hash160" => "Neo.UInt160",
                "Hash256" => "Neo.UInt256",
                "Integer" => "System.Numerics.BigInteger",
                "InteropInterface" => "Neo.VM.Types.InteropInterface",
                "PublicKey" => "Neo.Cryptography.ECC.ECPoint",
                "Map" => "Neo.VM.Types.Map",
                "Signature" => "Neo.VM.Types.ByteString",
                "String" => "string",
                "Void" => "void",
                _ => throw new FormatException($"Invalid parameter type {parameterType}")
            };
        }
    }
}
