// Copyright (C) 2015-2026 The Neo Project.
//
// RustCodeBuilder.cs file belongs to the neo project and is free
// software distributed under the MIT software license, see the
// accompanying file LICENSE in the main directory of the
// repository or http://www.opensource.org/licenses/mit-license.php
// for more details.
//
// Redistribution and use in source and binary forms with or without
// modifications are permitted.

using System.Collections.Generic;
using System.Text;

namespace Neo.Compiler.Backend.RiscV;

/// <summary>
/// StringBuilder wrapper that constructs Rust source code for a contract.
/// Accumulates method bodies and produces a complete PolkaVM-compatible
/// main.rs file with entry point harness, allocator, panic handler, and
/// dispatch function.
/// </summary>
internal class RustCodeBuilder
{
    private readonly StringBuilder _methods = new();
    private readonly List<string> _methodNames = new();
    private StringBuilder? _currentMethod;
    private int _indent = 0;
    private int _labelCounter = 0;

    public void BeginMethod(string name)
    {
        _currentMethod = new StringBuilder();
        _methodNames.Add(name);
        _currentMethod.AppendLine($"fn method_{SanitizeName(name)}(ctx: &mut Context) {{");
        _indent = 1;
    }

    public void EndMethod()
    {
        _currentMethod!.AppendLine("}");
        _methods.Append(_currentMethod);
        _methods.AppendLine();
        _currentMethod = null;
        _indent = 0;
    }

    public void Line(string code)
    {
        var target = _currentMethod ?? _methods;
        target.Append(new string(' ', _indent * 4));
        target.AppendLine(code);
    }

    public string NewLabel() => $"label_{_labelCounter++}";

    /// <summary>
    /// Builds a complete main.rs with PolkaVM entry point harness.
    /// The generated file is a standalone no_std/no_main binary that:
    /// - Declares PolkaVM imports (host_call)
    /// - Sets up a bump allocator with a 4MB arena
    /// - Provides execute/get_result_ptr/get_result_len exports
    /// - Contains all generated method bodies and a dispatch function
    /// </summary>
    public string Build(string contractName)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine($"// Generated PolkaVM contract for: {contractName}");
        sb.AppendLine("// Auto-generated by the Neo C# to RISC-V compiler. Do not edit.");
        sb.AppendLine();

        // Crate attributes
        sb.AppendLine("#![no_std]");
        sb.AppendLine("#![no_main]");
        sb.AppendLine("#![allow(unused)]");
        sb.AppendLine();

        // Extern crate and imports
        sb.AppendLine("extern crate alloc;");
        sb.AppendLine();
        sb.AppendLine("use neo_riscv_rt::Context;");
        sb.AppendLine("use neo_riscv_rt::stack_value::StackValue;");
        sb.AppendLine("use neo_riscv_contract_harness::{decode_entry, encode_result, bridge_syscall, set_host_call};");
        sb.AppendLine();

        // PolkaVM host imports
        sb.AppendLine("// === PolkaVM host imports ===");
        sb.AppendLine("#[polkavm_derive::polkavm_import]");
        sb.AppendLine("extern \"C\" {");
        sb.AppendLine("    fn host_call(api: u32, ip: u32, stack_ptr: u32, stack_len: u32, result_ptr: u32, result_cap: u32) -> u32;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Allocator (simple bump allocator using a static arena)
        sb.AppendLine("// === Allocator ===");
        sb.AppendLine("mod bump_alloc {");
        sb.AppendLine("    use core::alloc::{GlobalAlloc, Layout};");
        sb.AppendLine("    use core::cell::UnsafeCell;");
        sb.AppendLine("    use core::sync::atomic::{AtomicUsize, Ordering};");
        sb.AppendLine();
        sb.AppendLine("    const ARENA_SIZE: usize = 4 * 1024 * 1024;");
        sb.AppendLine();
        sb.AppendLine("    #[repr(C, align(16))]");
        sb.AppendLine("    struct Arena {");
        sb.AppendLine("        data: UnsafeCell<[u8; ARENA_SIZE]>,");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    unsafe impl Sync for Arena {}");
        sb.AppendLine();
        sb.AppendLine("    pub struct BumpAllocator {");
        sb.AppendLine("        arena: Arena,");
        sb.AppendLine("        offset: AtomicUsize,");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    impl BumpAllocator {");
        sb.AppendLine("        pub const fn new() -> Self {");
        sb.AppendLine("            Self {");
        sb.AppendLine("                arena: Arena { data: UnsafeCell::new([0u8; ARENA_SIZE]) },");
        sb.AppendLine("                offset: AtomicUsize::new(0),");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    unsafe impl GlobalAlloc for BumpAllocator {");
        sb.AppendLine("        unsafe fn alloc(&self, layout: Layout) -> *mut u8 {");
        sb.AppendLine("            let align = layout.align();");
        sb.AppendLine("            let size = layout.size();");
        sb.AppendLine("            loop {");
        sb.AppendLine("                let current = self.offset.load(Ordering::Relaxed);");
        sb.AppendLine("                let aligned = (current + align - 1) & !(align - 1);");
        sb.AppendLine("                let new_offset = aligned + size;");
        sb.AppendLine("                if new_offset > ARENA_SIZE {");
        sb.AppendLine("                    return core::ptr::null_mut();");
        sb.AppendLine("                }");
        sb.AppendLine("                if self.offset.compare_exchange_weak(");
        sb.AppendLine("                    current, new_offset, Ordering::Relaxed, Ordering::Relaxed");
        sb.AppendLine("                ).is_ok() {");
        sb.AppendLine("                    let base = self.arena.data.get() as *mut u8;");
        sb.AppendLine("                    return base.add(aligned);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        unsafe fn dealloc(&self, _ptr: *mut u8, _layout: Layout) {");
        sb.AppendLine("            // Bump allocator does not reclaim memory.");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#[global_allocator]");
        sb.AppendLine("static ALLOCATOR: bump_alloc::BumpAllocator = bump_alloc::BumpAllocator::new();");
        sb.AppendLine();

        // Result buffer
        sb.AppendLine("// === Result buffer ===");
        sb.AppendLine("const MAX_RESULT_SIZE: usize = 256 * 1024;");
        sb.AppendLine("static mut RESULT_BUF: [u8; MAX_RESULT_SIZE] = [0u8; MAX_RESULT_SIZE];");
        sb.AppendLine("static mut RESULT_LEN: u32 = 0;");
        sb.AppendLine();

        // Entry points
        sb.AppendLine("// === PolkaVM entry points ===");
        sb.AppendLine();
        sb.AppendLine("#[polkavm_derive::polkavm_export]");
        sb.AppendLine("pub extern \"C\" fn execute(stack_ptr: u32, stack_len: u32) {");
        sb.AppendLine("    // Register the host_call import and syscall bridge before any contract code runs.");
        sb.AppendLine("    set_host_call(host_call);");
        sb.AppendLine("    neo_riscv_rt::set_syscall_bridge(bridge_syscall);");
        sb.AppendLine();
        sb.AppendLine("    let stack_data = unsafe {");
        sb.AppendLine("        core::slice::from_raw_parts(stack_ptr as *const u8, stack_len as usize)");
        sb.AppendLine("    };");
        sb.AppendLine("    let entry = decode_entry(stack_data);");
        sb.AppendLine("    let method = core::str::from_utf8(&entry.method_name).unwrap_or(\"\");");
        sb.AppendLine("    let mut ctx = entry.ctx;");
        sb.AppendLine("    dispatch(&mut ctx, method);");
        sb.AppendLine("    let result_bytes = encode_result(ctx);");
        sb.AppendLine("    let len = result_bytes.len().min(MAX_RESULT_SIZE);");
        sb.AppendLine("    unsafe {");
        sb.AppendLine("        RESULT_BUF[..len].copy_from_slice(&result_bytes[..len]);");
        sb.AppendLine("        RESULT_LEN = len as u32;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#[polkavm_derive::polkavm_export]");
        sb.AppendLine("pub extern \"C\" fn get_result_ptr() -> u32 {");
        sb.AppendLine("    unsafe { RESULT_BUF.as_ptr() as u32 }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#[polkavm_derive::polkavm_export]");
        sb.AppendLine("pub extern \"C\" fn get_result_len() -> u32 {");
        sb.AppendLine("    unsafe { RESULT_LEN }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Panic handler — fault via host call rather than hanging indefinitely
        sb.AppendLine("// === Panic handler ===");
        sb.AppendLine("#[panic_handler]");
        sb.AppendLine("fn panic(_info: &core::panic::PanicInfo) -> ! {");
        sb.AppendLine("    // Trigger a fault that the host can detect.");
        sb.AppendLine("    unsafe { core::arch::asm!(\"unimp\", options(noreturn)) }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Generated contract methods
        sb.AppendLine("// === Generated contract methods ===");
        sb.AppendLine();
        sb.Append(_methods);

        // Dispatch function
        sb.AppendLine("// === Dispatch ===");
        sb.AppendLine();
        sb.AppendLine("fn dispatch(ctx: &mut Context, method: &str) {");
        sb.AppendLine("    match method {");
        foreach (var name in _methodNames)
            sb.AppendLine($"        \"{name}\" => method_{SanitizeName(name)}(ctx),");
        sb.AppendLine("        _ => ctx.fault(\"Unknown method\"),");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a Cargo.toml for the contract crate.
    /// </summary>
    /// <param name="contractName">The display name of the contract.</param>
    /// <param name="cratesPath">
    /// Relative path from the generated crate to the neo-riscv-vm/crates directory.
    /// For example, "../../../crates" if the output is in bin/sc/ContractName/.
    /// </param>
    public static string BuildCargoToml(string contractName, string cratesPath)
    {
        string crateName = SanitizeName(contractName);
        var sb = new StringBuilder();
        sb.AppendLine($"# Generated Cargo.toml for contract: {contractName}");
        sb.AppendLine();
        sb.AppendLine("[package]");
        sb.AppendLine($"name = \"{crateName}\"");
        sb.AppendLine("version = \"0.1.0\"");
        sb.AppendLine("edition = \"2021\"");
        sb.AppendLine();
        sb.AppendLine("[dependencies]");
        sb.AppendLine($"neo-riscv-abi = {{ path = \"{cratesPath}/neo-riscv-abi\" }}");
        sb.AppendLine($"neo-riscv-rt = {{ path = \"{cratesPath}/neo-riscv-rt\", default-features = false }}");
        sb.AppendLine($"neo-riscv-contract-harness = {{ path = \"{cratesPath}/neo-riscv-contract-harness\" }}");
        sb.AppendLine("polkavm-derive = \"0.32.0\"");
        sb.AppendLine("postcard = { version = \"1.1.3\", features = [\"alloc\"] }");
        sb.AppendLine();
        sb.AppendLine("[profile.release]");
        sb.AppendLine("opt-level = \"z\"");
        sb.AppendLine("lto = true");
        sb.AppendLine("panic = \"abort\"");
        return sb.ToString();
    }

    internal static string SanitizeName(string name) =>
        name.Replace("-", "_").Replace(".", "_").ToLowerInvariant();
}
