using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_Syscall_Out(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Syscall_Out"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""testByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":0,""safe"":false},{""name"":""testSByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":93,""safe"":false},{""name"":""testShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":183,""safe"":false},{""name"":""testUShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":273,""safe"":false},{""name"":""testIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":371,""safe"":false},{""name"":""testUIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":467,""safe"":false},{""name"":""testLongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":572,""safe"":false},{""name"":""testULongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":668,""safe"":false},{""name"":""testBoolTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":781,""safe"":false},{""name"":""_initialize"",""parameters"":[],""returntype"":""Void"",""offset"":998,""safe"":false}],""events"":[]},""permissions"":[{""contract"":""0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0"",""methods"":[""atoi""]}],""trusts"":[],""extra"":{""Version"":""3.10.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA7znO4OTpJcbCoGp54UQN2G/OrARhdG9pAQABBQAA/ekDVwQBeHEQSmFpRnFp2CREacpKciY+EHNpEM4ALSgLaRDOACsoBCIIahEoKBFza2ouEWlrzgAwADq7JhhrnHMi72k3AABKEAEAAbsmBmAIIgZFEGAJWGFwaFlQEr9AVwQBeHEQSmNpRnFp2CRBacpKciY7EHNpEM4ALSgLaRDOACsoBCIIahEoJRFza2ouEWlrzgAwADq7JhVrnHMi72k3AABKyhEsBmIIIgZFEGIJWmNwaFtQEr9AVwQBeHEQSmVpRnFp2CRBacpKciY7EHNpEM4ALSgLaRDOACsoBCIIahEoJRFza2ouEWlrzgAwADq7JhVrnHMi72k3AABKyhIsBmQIIgZFEGQJXGVwaF1QEr9AVwQBeHEQSmcHaUZxadgkRmnKSnImQBBzaRDOAC0oC2kQzgArKAQiCGoRKCoRc2tqLhFpa84AMAA6uyYaa5xzIu9pNwAAShACAAABALsmBmYIIgZFEGYJXmcHcGhfB1ASv0BXBAF4cRBKZwlpRnFp2CRCacpKciY8EHNpEM4ALSgLaRDOACsoBCIIahEoJhFza2ouEWlrzgAwADq7JhZrnHMi72k3AABKyhQsB2cICCIHRRBnCAlfCGcJcGhfCVASv0BXBAF4cRBKZwtpRnFp2CRLacpKciZFEHNpEM4ALSgLaRDOACsoBCIIahEoLxFza2ouEWlrzgAwADq7Jh9rnHMi72k3AABKEAMAAAAAAQAAALsmB2cKCCIHRRBnCglfCmcLcGhfC1ASv0BXBAF4cRBKZw1pRnFp2CRCacpKciY8EHNpEM4ALSgLaRDOACsoBCIIahEoJhFza2ouEWlrzgAwADq7JhZrnHMi72k3AABKyhgsB2cMCCIHRRBnDAlfDGcNcGhfDVASv0BXBAF4cRBKZw9pRnFp2CRTacpKciZNEHNpEM4ALSgLaRDOACsoBCIIahEoNxFza2ouEWlrzgAwADq7JidrnHMi72k3AABKEAQAAAAAAAAAAAEAAAAAAAAAuyYHZw4IIgdFEGcOCV8OZw9waF8PUBK/QFcCAXhxCUpnEWlGSgwEdHJ1ZZclsAAAAEoMBWZhbHNllyWnAAAASgwEVFJVRZcllQAAAEoMBFRydWWXJYgAAABKDAF0lyR+SgwBVJckd0oMATGXJHBKDAN5ZXOXJGdKDANZRVOXJF5KDAF5lyRXSgwBWZckUEoMBUZBTFNFlyRKSgwFRmFsc2WXJD9KDAFmlyQ4SgwBRpckMUoMATCXJCpKDAJub5ckIkoMAk5PlyQaSgwBbpckE0oMAU6XJAxFCQkiCkUICCIFRQgJZxBfEGcRcGhfEVASv0BWEkD0+bwS").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIBeHEJSmcRaUZKDAR0cnVllyWwAAAASgwFZmFsc2WXJacAAABKDARUUlVFlyWVAAAASgwEVHJ1ZZcliAAAAEoMAXSXJH5KDAFUlyR3SgwBMZckcEoMA3llc5ckZ0oMA1lFU5ckXkoMAXmXJFdKDAFZlyRQSgwFRkFMU0WXJEpKDAVGYWxzZZckP0oMAWaXJDhKDAFGlyQxSgwBMJckKkoMAm5vlyQiSgwCTk+XJBpKDAFulyQTSgwBTpckDEUJCSIKRQgIIgVFCAlnEF8QZxFwaF8RUBK/QA==
    /// INITSLOT 0201 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74727565 'true' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L B0000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66616C7365 'false' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L A7000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54525545 'TRUE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 95000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54727565 'True' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 88000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74 't' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 7E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54 'T' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 77 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 70 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 796573 'yes' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 67 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 594553 'YES' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 5E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 79 'y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 57 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 59 'Y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 50 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46414C5345 'FALSE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 4A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46616C7365 'False' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 3F [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66 'f' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 38 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46 'F' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 31 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 2A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E6F 'no' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 22 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E4F 'NO' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 1A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E 'n' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 13 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E 'N' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHF [1 datoshi]
    /// PUSHF [1 datoshi]
    /// JMP 0A [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSHF [1 datoshi]
    /// STSFLD 10 [2 datoshi]
    /// LDSFLD 10 [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 11 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testBoolTryParse")]
    public abstract IList<object>? TestBoolTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmFpRnFp2CREacpKciY+EHNpEM4ALSgLaRDOACsoBCIIahEoKBFza2ouEWlrzgAwADq7JhhrnHMi72k3AABKEAEAAbsmBmAIIgZFEGAJWGFwaFlQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 44 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3E [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 28 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 18 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT16 0001 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD0 [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testByteTryParse")]
    public abstract IList<object>? TestByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcJaUZxadgkQmnKSnImPBBzaRDOAC0oC2kQzgArKAQiCGoRKCYRc2tqLhFpa84AMAA6uyYWa5xzIu9pNwAASsoULAdnCAgiB0UQZwgJXwhnCXBoXwlQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 42 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3C [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 26 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 16 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPGT 07 [2 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 08 [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 09 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testIntTryParse")]
    public abstract IList<object>? TestIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcNaUZxadgkQmnKSnImPBBzaRDOAC0oC2kQzgArKAQiCGoRKCYRc2tqLhFpa84AMAA6uyYWa5xzIu9pNwAASsoYLAdnDAgiB0UQZwwJXwxnDXBoXw1QEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 42 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3C [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 26 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 16 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH8 [1 datoshi]
    /// JMPGT 07 [2 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0C [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0D [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testLongTryParse")]
    public abstract IList<object>? TestLongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmNpRnFp2CRBacpKciY7EHNpEM4ALSgLaRDOACsoBCIIahEoJRFza2ouEWlrzgAwADq7JhVrnHMi72k3AABKyhEsBmIIIgZFEGIJWmNwaFtQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 41 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 25 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 15 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPGT 06 [2 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD2 [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD3 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testSByteTryParse")]
    public abstract IList<object>? TestSByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmVpRnFp2CRBacpKciY7EHNpEM4ALSgLaRDOACsoBCIIahEoJRFza2ouEWlrzgAwADq7JhVrnHMi72k3AABKyhIsBmQIIgZFEGQJXGVwaF1QEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 41 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 25 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 15 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPGT 06 [2 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD4 [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD5 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testShortTryParse")]
    public abstract IList<object>? TestShortTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcLaUZxadgkS2nKSnImRRBzaRDOAC0oC2kQzgArKAQiCGoRKC8Rc2tqLhFpa84AMAA6uyYfa5xzIu9pNwAAShADAAAAAAEAAAC7JgdnCggiB0UQZwoJXwpnC3BoXwtQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 4B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 45 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 2F [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1F [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0A [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0B [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUIntTryParse")]
    public abstract IList<object>? TestUIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcPaUZxadgkU2nKSnImTRBzaRDOAC0oC2kQzgArKAQiCGoRKDcRc2tqLhFpa84AMAA6uyYna5xzIu9pNwAAShAEAAAAAAAAAAABAAAAAAAAALsmB2cOCCIHRRBnDglfDmcPcGhfD1ASv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 53 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 4D [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 37 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 27 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT128 00000000000000000100000000000000 [4 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0E [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0F [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testULongTryParse")]
    public abstract IList<object>? TestULongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcHaUZxadgkRmnKSnImQBBzaRDOAC0oC2kQzgArKAQiCGoRKCoRc2tqLhFpa84AMAA6uyYaa5xzIu9pNwAAShACAAABALsmBmYIIgZFEGYJXmcHcGhfB1ASv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 46 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 40 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 04 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 2A [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPGE 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1A [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EF [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT32 00000100 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD6 [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 07 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUShortTryParse")]
    public abstract IList<object>? TestUShortTryParse(string? s);

    #endregion
}
