using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_Enum(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Enum"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""testUlongEnumGetName"",""parameters"":[{""name"":""value"",""type"":""Integer""}],""returntype"":""String"",""offset"":0,""safe"":false},{""name"":""testEnumParse"",""parameters"":[{""name"":""value"",""type"":""String""}],""returntype"":""Any"",""offset"":53,""safe"":false},{""name"":""testEnumParseWithContinuation"",""parameters"":[],""returntype"":""Integer"",""offset"":137,""safe"":false},{""name"":""testEnumParseIgnoreCase"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""ignoreCase"",""type"":""Boolean""}],""returntype"":""Any"",""offset"":1144,""safe"":false},{""name"":""testEnumParseIgnoreCaseFromExpression"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""caseSensitive"",""type"":""Boolean""}],""returntype"":""Any"",""offset"":1334,""safe"":false},{""name"":""testEnumTryParse"",""parameters"":[{""name"":""value"",""type"":""String""}],""returntype"":""Boolean"",""offset"":1605,""safe"":false},{""name"":""testEnumTryParseIgnoreCase"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""ignoreCase"",""type"":""Boolean""}],""returntype"":""Boolean"",""offset"":1677,""safe"":false},{""name"":""testEnumTryParseIgnoreCaseFromExpression"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""caseSensitive"",""type"":""Boolean""}],""returntype"":""Boolean"",""offset"":1857,""safe"":false},{""name"":""testEnumGetNames"",""parameters"":[],""returntype"":""Array"",""offset"":2044,""safe"":false},{""name"":""testEnumGetValues"",""parameters"":[],""returntype"":""Array"",""offset"":2081,""safe"":false},{""name"":""testEnumIsDefined"",""parameters"":[{""name"":""value"",""type"":""Any""}],""returntype"":""Boolean"",""offset"":2097,""safe"":false},{""name"":""testEnumIsDefinedByName"",""parameters"":[{""name"":""name"",""type"":""String""}],""returntype"":""Boolean"",""offset"":2139,""safe"":false},{""name"":""testEnumGetName"",""parameters"":[{""name"":""value"",""type"":""Integer""}],""returntype"":""String"",""offset"":2202,""safe"":false},{""name"":""testEnumGetNameWithType"",""parameters"":[{""name"":""value"",""type"":""Any""}],""returntype"":""String"",""offset"":2250,""safe"":false},{""name"":""testEnumHasFlag"",""parameters"":[{""name"":""value"",""type"":""Integer""},{""name"":""flag"",""type"":""Integer""}],""returntype"":""Boolean"",""offset"":2299,""safe"":false},{""name"":""testEnumToString"",""parameters"":[{""name"":""value"",""type"":""Integer""}],""returntype"":""String"",""offset"":2308,""safe"":false},{""name"":""testEnumToStringUnknown"",""parameters"":[{""name"":""value"",""type"":""Integer""}],""returntype"":""String"",""offset"":2358,""safe"":false},{""name"":""testEnumParseGeneric"",""parameters"":[{""name"":""value"",""type"":""String""}],""returntype"":""Integer"",""offset"":2408,""safe"":false},{""name"":""testEnumParseGenericIgnoreCase"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""ignoreCase"",""type"":""Boolean""}],""returntype"":""Integer"",""offset"":2510,""safe"":false},{""name"":""testEnumTryParseGeneric"",""parameters"":[{""name"":""value"",""type"":""String""}],""returntype"":""Boolean"",""offset"":2656,""safe"":false},{""name"":""testEnumTryParseGenericIgnoreCase"",""parameters"":[{""name"":""value"",""type"":""String""},{""name"":""ignoreCase"",""type"":""Boolean""}],""returntype"":""Boolean"",""offset"":2739,""safe"":false},{""name"":""testEnumGetValuesGeneric"",""parameters"":[],""returntype"":""Array"",""offset"":2866,""safe"":false},{""name"":""testEnumGetNamesGeneric"",""parameters"":[],""returntype"":""Array"",""offset"":2872,""safe"":false},{""name"":""_initialize"",""parameters"":[],""returntype"":""Void"",""offset"":2899,""safe"":false}],""events"":[]},""permissions"":[{""contract"":""0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0"",""methods"":[""itoa""]}],""trusts"":[],""extra"":{""Version"":""3.10.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA7znO4OTpJcbCoGp54UQN2G/OrARpdG9hAQABBQAA/VYLVwEBeHBoESgYaAT//////////wAAAAAAAAAAKA0iFgwGVmFsdWUxQAwITWF4VmFsdWVAC0BXAAEMCFRlc3RFbnVteEZKDAZWYWx1ZTGXJgURIjZKDAZWYWx1ZTKXJgUSIidKDAZWYWx1ZTOXJgUTIhhFDBJObyBzdWNoIGVudW0gdmFsdWU6RkBXCQAMCFRlc3RFbnVtDAZWYWx1ZTFGSgwGVmFsdWUxlyYFESI2SgwGVmFsdWUylyYFEiInSgwGVmFsdWUzlyYFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOkZwDAhUZXN0RW51bQwGdmFsdWUyRnIMABBKasouNkpqUM5KAGEAe7skIEoQMghKAYAAMA9FSmpQEYxRUItQnCLaUVCLUJwi0wAgn1FQi1CcIslF2yhKDAZWQUxVRTGXJgZFESI4SgwGVkFMVUUylyYGRRIiKEoMBlZBTFVFM5cmBkUTIhhFDBJObyBzdWNoIGVudW0gdmFsdWU6cQwIVGVzdEVudW0MBlZhbHVlMkZKDAZWYWx1ZTGXJgZFESI4SgwGVmFsdWUylyYGRRIiKEoMBlZhbHVlM5cmBkUTIhhFDBJObyBzdWNoIGVudW0gdmFsdWU6cgwGVmFsdWUxSgwGVmFsdWUxlyYFESI2SgwGVmFsdWUylyYFEiInSgwGVmFsdWUzlyYFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOkZzDAZWQUxVRTMIdm4mRncHDAAQSm8Hyi44Sm8HUM5KAGEAe7skIUoQMghKAYAAMBBFSm8HUBGMUVCLUJwi11FQi1CcItAAIJ9RUItQnCLGRdsoSm4mDAwGVkFMVUUxIgoMBlZhbHVlMZcmBREiUEpuJgwMBlZBTFVFMiIKDAZWYWx1ZTKXJgUSIjRKbiYMDAZWQUxVRTMiCgwGVmFsdWUzlyYFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOkZ0DAZWYWx1ZTIJdwdvByZGdwgMABBKbwjKLjhKbwhQzkoAYQB7uyQhShAyCEoBgAAwEEVKbwhQEYxRUItQnCLXUVCLUJwi0AAgn1FQi1CcIsZF2yhKbwcmDAwGVkFMVUUxIgoMBlZhbHVlMZcmBREiUkpvByYMDAZWQUxVRTIiCgwGVmFsdWUylyYFEiI1Sm8HJgwMBlZBTFVFMyIKDAZWYWx1ZTOXJgUTIhhFDBJObyBzdWNoIGVudW0gdmFsdWU6RnVoaZ5KyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9qnkrKFDIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn2ueSsoUMh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfbJ5KyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9tnkrKFDIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAnxqeSsoUMh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfQFcCAgwIVGVzdEVudW14eXBGaCZCcQwAEEppyi42SmlQzkoAYQB7uyQgShAyCEoBgAAwD0VKaVARjFFQi1CcItpRUItQnCLTACCfUVCLUJwiyUXbKEpoJgwMBlZBTFVFMSIKDAZWYWx1ZTGXJgVFEUBKaCYMDAZWQUxVRTIiCgwGVmFsdWUylyYFRRJASmgmDAwGVkFMVUUzIgoMBlZhbHVlM5cmBUUTQEUMEk5vIHN1Y2ggZW51bSB2YWx1ZTpXAgIMCFRlc3RFbnVtCXg1tgAAAHmqcEZoJkJxDAAQSmnKLjZKaVDOSgBhAHu7JCBKEDIISgGAADAPRUppUBGMUVCLUJwi2lFQi1CcItMAIJ9RUItQnCLJRdsoSmgmDAwGVkFMVUUxIgoMBlZhbHVlMZcmBUURQEpoJgwMBlZBTFVFMiIKDAZWYWx1ZTKXJgVFEkBKaCYMDAZWQUxVRTMiCgwGVmFsdWUzlyYFRRNARQwSTm8gc3VjaCBlbnVtIHZhbHVlOlcBAnkmRHhwDAAQSmjKLjZKaFDOSgBhAHu7JCBKEDIISgGAADAPRUpoUBGMUVCLUJwi2lFQi1CcItMAIJ9RUItQnCLJRdsoQHhAVwABDAhUZXN0RW51bXgLYUoMBlZhbHVlMZcmBggRIiRKDAZWYWx1ZTKXJgYIEiIUSgwGVmFsdWUzlyYGCBMiBAkQYEZGWGFAVwICDAhUZXN0RW51bXh5C2NKcCZCcQwAEEppyi42SmlQzkoAYQB7uyQgShAyCEoBgAAwD0VKaVARjFFQi1CcItpRUItQnCLTACCfUVCLUJwiyUXbKEZKaCYMDAZWQUxVRTEiCgwGVmFsdWUxlyYGCBEiPkpoJgwMBlZBTFVFMiIKDAZWYWx1ZTKXJgYIEiIhSmgmDAwGVkFMVUUzIgoMBlZhbHVlM5cmBggTIgQJEGJGWmNAVwICDAhUZXN0RW51bQl4Nav+//95qgtkSnAmQnEMABBKacouNkppUM5KAGEAe7skIEoQMghKAYAAMA9FSmlQEYxRUItQnCLaUVCLUJwi0wAgn1FQi1CcIslF2yhGSmgmDAwGVkFMVUUxIgoMBlZhbHVlMZcmBggRIj5KaCYMDAZWQUxVRTIiCgwGVmFsdWUylyYGCBIiIUpoJgwMBlZBTFVFMyIKDAZWYWx1ZTOXJgYIEyIECRBiRlpkQAwIVGVzdEVudW0MBlZhbHVlMwwGVmFsdWUyDAZWYWx1ZTETwEAMCFRlc3RFbnVtExIRE8BAVwABDAhUZXN0RW51bXhKEZcmBQgiE0oSlyYFCCILShOXJgUIIgMJRkZAVwABDAhUZXN0RW51bXhKDAZWYWx1ZTGXJgUIIiFKDAZWYWx1ZTKXJgUIIhJKDAZWYWx1ZTOXJgUIIgMJRkZAVwEBeHBoESgMaBIoEWgTKBYiHQwGVmFsdWUxQAwGVmFsdWUyQAwGVmFsdWUzQAtAVwABeEoRKgxFDAZWYWx1ZTFAShIqDEUMBlZhbHVlMkBKEyoMRQwGVmFsdWUzQEULQFcAAnh5TpGzQFcAAXhKESoMRQwGVmFsdWUxQEoSKgxFDAZWYWx1ZTJAShMqDEUMBlZhbHVlM0A3AABAVwABeEoRKgxFDAZWYWx1ZTFAShIqDEUMBlZhbHVlMkBKEyoMRQwGVmFsdWUzQDcAAEBXAQEJeDWO/P//cGgMBlZhbHVlMZcmBBFAaAwGVmFsdWUylyYEEkBoDAZWYWx1ZTOXJgQTQAgmFwwSTm8gc3VjaCBlbnVtIHZhbHVlOgwWTm8gc3dpdGNoIGFybSBtYXRjaGVkLjpXAgJ5eDUo/P//cGhxaQwGVkFMVUUxlyYEEUBpDAZWQUxVRTKXJgQSQGkMBlZBTFVFM5cmBBNAaQwGVmFsdWUxlyYEEUBpDAZWYWx1ZTKXJgQSQGkMBlZhbHVlM5cmBBNACCYXDBJObyBzdWNoIGVudW0gdmFsdWU6DBZObyBzd2l0Y2ggYXJtIG1hdGNoZWQuOlcBAQl4NZb7//9waAwGVmFsdWUxlyYECEBoDAZWYWx1ZTKXJgQIQGgMBlZhbHVlM5cmBAhACCYECUAMFk5vIHN3aXRjaCBhcm0gbWF0Y2hlZC46VwICeXg1Q/v//3BocWkMBlZBTFVFMZcmBAhAaQwGVkFMVUUylyYECEBpDAZWQUxVRTOXJgQIQGkMBlZhbHVlMZcmBAhAaQwGVmFsdWUylyYECEBpDAZWYWx1ZTOXJgQIQAgmBAlADBZObyBzd2l0Y2ggYXJtIG1hdGNoZWQuOhMSERPAQAwGVmFsdWUzDAZWYWx1ZTIMBlZhbHVlMRPAQFYFQB91Ftw=").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBeHBoESgMaBIoEWgTKBYiHQwGVmFsdWUxQAwGVmFsdWUyQAwGVmFsdWUzQAtA
    /// INITSLOT 0101 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 0C [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPEQ 11 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMPEQ 16 [2 datoshi]
    /// JMP 1D [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// RET [0 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// RET [0 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// RET [0 datoshi]
    /// PUSHNULL [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetName")]
    public abstract string? TestEnumGetName(BigInteger? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: DAhUZXN0RW51bQwGVmFsdWUzDAZWYWx1ZTIMBlZhbHVlMRPAQA==
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetNames")]
    public abstract IList<object>? TestEnumGetNames();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: DAZWYWx1ZTMMBlZhbHVlMgwGVmFsdWUxE8BA
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetNamesGeneric")]
    public abstract IList<object>? TestEnumGetNamesGeneric();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABeEoRKgxFDAZWYWx1ZTFAShIqDEUMBlZhbHVlMkBKEyoMRQwGVmFsdWUzQEULQA==
    /// INITSLOT 0001 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// RET [0 datoshi]
    /// DROP [2 datoshi]
    /// PUSHNULL [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetNameWithType")]
    public abstract string? TestEnumGetNameWithType(object? value = null);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: DAhUZXN0RW51bRMSERPAQA==
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSH3 [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetValues")]
    public abstract IList<object>? TestEnumGetValues();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: ExIRE8BA
    /// PUSH3 [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumGetValuesGeneric")]
    public abstract IList<object>? TestEnumGetValuesGeneric();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwACeHlOkbNA
    /// INITSLOT 0002 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// LDARG1 [2 datoshi]
    /// TUCK [2 datoshi]
    /// AND [8 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumHasFlag")]
    public abstract bool? TestEnumHasFlag(BigInteger? value, BigInteger? flag);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABDAhUZXN0RW51bXhKEZcmBQgiE0oSlyYFCCILShOXJgUIIgMJRkZA
    /// INITSLOT 0001 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 13 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 0B [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 03 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// NIP [2 datoshi]
    /// NIP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumIsDefined")]
    public abstract bool? TestEnumIsDefined(object? value = null);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABDAhUZXN0RW51bXhKDAZWYWx1ZTGXJgUIIiFKDAZWYWx1ZTKXJgUIIhJKDAZWYWx1ZTOXJgUIIgMJRkZA
    /// INITSLOT 0001 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 21 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 12 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 03 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// NIP [2 datoshi]
    /// NIP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumIsDefinedByName")]
    public abstract bool? TestEnumIsDefinedByName(string? name);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABDAhUZXN0RW51bXhGSgwGVmFsdWUxlyYFESI2SgwGVmFsdWUylyYFEiInSgwGVmFsdWUzlyYFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOkZA
    /// INITSLOT 0001 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 27 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// NIP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumParse")]
    public abstract object? TestEnumParse(string? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBCXg1jvz//3BoDAZWYWx1ZTGXJgQRQGgMBlZhbHVlMpcmBBJAaAwGVmFsdWUzlyYEE0AIJhcMEk5vIHN1Y2ggZW51bSB2YWx1ZToMFk5vIHN3aXRjaCBhcm0gbWF0Y2hlZC46
    /// INITSLOT 0101 [64 datoshi]
    /// PUSHF [1 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L 8EFCFFFF [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHT [1 datoshi]
    /// JMPIFNOT 17 [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// PUSHDATA1 4E6F207377697463682061726D206D6174636865642E [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumParseGeneric")]
    public abstract BigInteger? TestEnumParseGeneric(string? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICeXg1KPz//3BocWkMBlZBTFVFMZcmBBFAaQwGVkFMVUUylyYEEkBpDAZWQUxVRTOXJgQTQGkMBlZhbHVlMZcmBBFAaQwGVmFsdWUylyYEEkBpDAZWYWx1ZTOXJgQTQAgmFwwSTm8gc3VjaCBlbnVtIHZhbHVlOgwWTm8gc3dpdGNoIGFybSBtYXRjaGVkLjo=
    /// INITSLOT 0202 [64 datoshi]
    /// LDARG1 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L 28FCFFFF [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHT [1 datoshi]
    /// JMPIFNOT 17 [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// PUSHDATA1 4E6F207377697463682061726D206D6174636865642E [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumParseGenericIgnoreCase")]
    public abstract BigInteger? TestEnumParseGenericIgnoreCase(string? value, bool? ignoreCase);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICDAhUZXN0RW51bXh5cEZoJkJxDAAQSmnKLjZKaVDOSgBhAHu7JCBKEDIISgGAADAPRUppUBGMUVCLUJwi2lFQi1CcItMAIJ9RUItQnCLJRdsoSmgmDAwGVkFMVUUxIgoMBlZhbHVlMZcmBUURQEpoJgwMBlZBTFVFMiIKDAZWYWx1ZTKXJgVFEkBKaCYMDAZWQUxVRTMiCgwGVmFsdWUzlyYFRRNARQwSTm8gc3VjaCBlbnVtIHZhbHVlOg==
    /// INITSLOT 0202 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// LDARG1 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// NIP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 42 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 0F [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP DA [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D3 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C9 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumParseIgnoreCase")]
    public abstract object? TestEnumParseIgnoreCase(string? value, bool? ignoreCase);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICDAhUZXN0RW51bQl4NbYAAAB5qnBGaCZCcQwAEEppyi42SmlQzkoAYQB7uyQgShAyCEoBgAAwD0VKaVARjFFQi1CcItpRUItQnCLTACCfUVCLUJwiyUXbKEpoJgwMBlZBTFVFMSIKDAZWYWx1ZTGXJgVFEUBKaCYMDAZWQUxVRTIiCgwGVmFsdWUylyYFRRJASmgmDAwGVkFMVUUzIgoMBlZhbHVlM5cmBUUTQEUMEk5vIHN1Y2ggZW51bSB2YWx1ZTo=
    /// INITSLOT 0202 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHF [1 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L B6000000 [512 datoshi]
    /// LDARG1 [2 datoshi]
    /// NOT [4 datoshi]
    /// STLOC0 [2 datoshi]
    /// NIP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 42 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 0F [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP DA [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D3 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C9 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumParseIgnoreCaseFromExpression")]
    public abstract object? TestEnumParseIgnoreCaseFromExpression(string? value, bool? caseSensitive);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwkADAhUZXN0RW51bQwGVmFsdWUxRkoMBlZhbHVlMZcmBREiNkoMBlZhbHVlMpcmBRIiJ0oMBlZhbHVlM5cmBRMiGEUMEk5vIHN1Y2ggZW51bSB2YWx1ZTpGcAwIVGVzdEVudW0MBnZhbHVlMkZyDAAQSmrKLjZKalDOSgBhAHu7JCBKEDIISgGAADAPRUpqUBGMUVCLUJwi2lFQi1CcItMAIJ9RUItQnCLJRdsoSgwGVkFMVUUxlyYGRREiOEoMBlZBTFVFMpcmBkUSIihKDAZWQUxVRTOXJgZFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOnEMCFRlc3RFbnVtDAZWYWx1ZTJGSgwGVmFsdWUxlyYGRREiOEoMBlZhbHVlMpcmBkUSIihKDAZWYWx1ZTOXJgZFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOnIMBlZhbHVlMUoMBlZhbHVlMZcmBREiNkoMBlZhbHVlMpcmBRIiJ0oMBlZhbHVlM5cmBRMiGEUMEk5vIHN1Y2ggZW51bSB2YWx1ZTpGcwwGVkFMVUUzCHZuJkZ3BwwAEEpvB8ouOEpvB1DOSgBhAHu7JCFKEDIISgGAADAQRUpvB1ARjFFQi1CcItdRUItQnCLQACCfUVCLUJwixkXbKEpuJgwMBlZBTFVFMSIKDAZWYWx1ZTGXJgURIlBKbiYMDAZWQUxVRTIiCgwGVmFsdWUylyYFEiI0Sm4mDAwGVkFMVUUzIgoMBlZhbHVlM5cmBRMiGEUMEk5vIHN1Y2ggZW51bSB2YWx1ZTpGdAwGVmFsdWUyCXcHbwcmRncIDAAQSm8Iyi44Sm8IUM5KAGEAe7skIUoQMghKAYAAMBBFSm8IUBGMUVCLUJwi11FQi1CcItAAIJ9RUItQnCLGRdsoSm8HJgwMBlZBTFVFMSIKDAZWYWx1ZTGXJgURIlJKbwcmDAwGVkFMVUUyIgoMBlZhbHVlMpcmBRIiNUpvByYMDAZWQUxVRTMiCgwGVmFsdWUzlyYFEyIYRQwSTm8gc3VjaCBlbnVtIHZhbHVlOkZ1aGmeSsoUMh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfap5KyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9rnkrKFDIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn2yeSsoUMh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfbZ5KyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ8ankrKFDIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn0A=
    /// INITSLOT 0900 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 27 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// NIP [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHDATA1 76616C756532 'value2' [8 datoshi]
    /// NIP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 0F [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP DA [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D3 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C9 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 38 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 28 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 38 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 28 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// STLOC2 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 27 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// NIP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// PUSHT [1 datoshi]
    /// STLOC6 [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// JMPIFNOT 46 [2 datoshi]
    /// STLOC 07 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 38 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 21 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 10 [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D7 [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D0 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C6 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 50 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 34 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// NIP [2 datoshi]
    /// STLOC4 [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// PUSHF [1 datoshi]
    /// STLOC 07 [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// JMPIFNOT 46 [2 datoshi]
    /// STLOC 08 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 38 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 21 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 10 [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D7 [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D0 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C6 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 52 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 35 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 18 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 4E6F207375636820656E756D2076616C7565 [8 datoshi]
    /// THROW [512 datoshi]
    /// NIP [2 datoshi]
    /// STLOC5 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// LDLOC2 [2 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// LDLOC3 [2 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// LDLOC4 [2 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// LDLOC5 [2 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// PUSH10 [1 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumParseWithContinuation")]
    public abstract BigInteger? TestEnumParseWithContinuation();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABeEoRKgxFDAZWYWx1ZTFAShIqDEUMBlZhbHVlMkBKEyoMRQwGVmFsdWUzQDcAAEA=
    /// INITSLOT 0001 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// RET [0 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumToString")]
    public abstract string? TestEnumToString(BigInteger? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABeEoRKgxFDAZWYWx1ZTFAShIqDEUMBlZhbHVlMkBKEyoMRQwGVmFsdWUzQDcAAEA=
    /// INITSLOT 0001 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// RET [0 datoshi]
    /// DUP [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMPNE 0C [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// RET [0 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumToStringUnknown")]
    public abstract string? TestEnumToStringUnknown(BigInteger? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwABDAhUZXN0RW51bXgLYUoMBlZhbHVlMZcmBggRIiRKDAZWYWx1ZTKXJgYIEiIUSgwGVmFsdWUzlyYGCBMiBAkQYEZGWGFA
    /// INITSLOT 0001 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STSFLD1 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 24 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 14 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 04 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD0 [2 datoshi]
    /// NIP [2 datoshi]
    /// NIP [2 datoshi]
    /// LDSFLD0 [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumTryParse")]
    public abstract bool? TestEnumTryParse(string? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBCXg1lvv//3BoDAZWYWx1ZTGXJgQIQGgMBlZhbHVlMpcmBAhAaAwGVmFsdWUzlyYECEAIJgQJQAwWTm8gc3dpdGNoIGFybSBtYXRjaGVkLjo=
    /// INITSLOT 0101 [64 datoshi]
    /// PUSHF [1 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L 96FBFFFF [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHT [1 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHDATA1 4E6F207377697463682061726D206D6174636865642E [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumTryParseGeneric")]
    public abstract bool? TestEnumTryParseGeneric(string? value);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICeXg1Q/v//3BocWkMBlZBTFVFMZcmBAhAaQwGVkFMVUUylyYECEBpDAZWQUxVRTOXJgQIQGkMBlZhbHVlMZcmBAhAaQwGVmFsdWUylyYECEBpDAZWYWx1ZTOXJgQIQAgmBAlADBZObyBzd2l0Y2ggYXJtIG1hdGNoZWQuOg==
    /// INITSLOT 0202 [64 datoshi]
    /// LDARG1 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L 43FBFFFF [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHT [1 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHDATA1 4E6F207377697463682061726D206D6174636865642E [8 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("testEnumTryParseGenericIgnoreCase")]
    public abstract bool? TestEnumTryParseGenericIgnoreCase(string? value, bool? ignoreCase);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICDAhUZXN0RW51bXh5C2NKcCZCcQwAEEppyi42SmlQzkoAYQB7uyQgShAyCEoBgAAwD0VKaVARjFFQi1CcItpRUItQnCLTACCfUVCLUJwiyUXbKEZKaCYMDAZWQUxVRTEiCgwGVmFsdWUxlyYGCBEiPkpoJgwMBlZBTFVFMiIKDAZWYWx1ZTKXJgYIEiIhSmgmDAwGVkFMVUUzIgoMBlZhbHVlM5cmBggTIgQJEGJGWmNA
    /// INITSLOT 0202 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// LDARG0 [2 datoshi]
    /// LDARG1 [2 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STSFLD3 [2 datoshi]
    /// DUP [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMPIFNOT 42 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 0F [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP DA [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D3 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C9 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 3E [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 21 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 04 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD2 [2 datoshi]
    /// NIP [2 datoshi]
    /// LDSFLD2 [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumTryParseIgnoreCase")]
    public abstract bool? TestEnumTryParseIgnoreCase(string? value, bool? ignoreCase);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwICDAhUZXN0RW51bQl4Nav+//95qgtkSnAmQnEMABBKacouNkppUM5KAGEAe7skIEoQMghKAYAAMA9FSmlQEYxRUItQnCLaUVCLUJwi0wAgn1FQi1CcIslF2yhGSmgmDAwGVkFMVUUxIgoMBlZhbHVlMZcmBggRIj5KaCYMDAZWQUxVRTIiCgwGVmFsdWUylyYGCBIiIUpoJgwMBlZBTFVFMyIKDAZWYWx1ZTOXJgYIEyIECRBiRlpkQA==
    /// INITSLOT 0202 [64 datoshi]
    /// PUSHDATA1 54657374456E756D 'TestEnum' [8 datoshi]
    /// PUSHF [1 datoshi]
    /// LDARG0 [2 datoshi]
    /// CALL_L ABFEFFFF [512 datoshi]
    /// LDARG1 [2 datoshi]
    /// NOT [4 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STSFLD4 [2 datoshi]
    /// DUP [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMPIFNOT 42 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHDATA1 [8 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// JMPGE 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 61 [1 datoshi]
    /// PUSHINT8 7B [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPLE 08 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// JMPLT 0F [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// SUBSTR [2048 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP DA [2 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP D3 [2 datoshi]
    /// PUSHINT8 20 [1 datoshi]
    /// SUB [8 datoshi]
    /// ROT [2 datoshi]
    /// SWAP [2 datoshi]
    /// CAT [2048 datoshi]
    /// SWAP [2 datoshi]
    /// INC [4 datoshi]
    /// JMP C9 [2 datoshi]
    /// DROP [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554531 'VALUE1' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMP 3E [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554532 'VALUE2' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756532 'Value2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMP 21 [2 datoshi]
    /// DUP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// JMPIFNOT 0C [2 datoshi]
    /// PUSHDATA1 56414C554533 'VALUE3' [8 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHDATA1 56616C756533 'Value3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// JMP 04 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD2 [2 datoshi]
    /// NIP [2 datoshi]
    /// LDSFLD2 [2 datoshi]
    /// STSFLD4 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testEnumTryParseIgnoreCaseFromExpression")]
    public abstract bool? TestEnumTryParseIgnoreCaseFromExpression(string? value, bool? caseSensitive);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBeHBoESgYaAT//////////wAAAAAAAAAAKA0iFgwGVmFsdWUxQAwITWF4VmFsdWVAC0A=
    /// INITSLOT 0101 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 18 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHINT128 FFFFFFFFFFFFFFFF0000000000000000 [4 datoshi]
    /// JMPEQ 0D [2 datoshi]
    /// JMP 16 [2 datoshi]
    /// PUSHDATA1 56616C756531 'Value1' [8 datoshi]
    /// RET [0 datoshi]
    /// PUSHDATA1 4D617856616C7565 'MaxValue' [8 datoshi]
    /// RET [0 datoshi]
    /// PUSHNULL [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUlongEnumGetName")]
    public abstract string? TestUlongEnumGetName(BigInteger? value);

    #endregion
}
