using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

namespace Neo.SmartContract.Testing;

public abstract class Contract_Break(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Break"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""breakInTryCatch"",""parameters"":[{""name"":""exception"",""type"":""Boolean""}],""returntype"":""Void"",""offset"":0,""safe"":false}],""events"":[]},""permissions"":[],""trusts"":[],""extra"":{""Version"":""3.8.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP2NAVcGAQwBAAwC/wA1VAEAABAMAf81WwEAAHAiG2hB81S/HXE7AAU9FwwBAQwC/wA1MAEAAD9oQZwI7Zwk4QwC/wA1PgEAAAwBAZc5EAwB/zUgAQAAcCJqaEHzVL8dcTsaLxByIg4MCWV4Y2VwdGlvbjpqE7Uk8T1JcjsABz0CPUkMAQAMAv8ANdgAAAA/DAL/ADXuAAAADAEAlzkSERATwEpyynMQdCIUamzOdQwBAgwC/wA1rAAAACIGbGsw7D9oQZwI7ZwkkgwC/wA1tAAAAAwBApc5EAwB/zWWAAAAcCJsaEHzVL8dcTsaThByahO1RXgmDgwJZXhjZXB0aW9uOj1LchBzaxO1JgJrEJc5Ow4TDAEDDAL/ADRHajp0PQI9NAwC/wA0WgwBA5c5DAECDAL/ADQsPwwC/wA0RQwBApc5DAEDDAL/ADQXP2hBnAjtnCSQDAL/ADQoDAEDlzlAVwACeXhBm/ZnzkHmPxiEQFcAAnl4Qfa0a+JB3zC4mkBXAAF4Qfa0a+JBkl3oMUCyaIrf").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwYBDAEADAL/ADVUAQAAEAwB/zVbAQAAcCIbaEHzVL8dcTsABT0XDAEBDAL/ADUwAQAAP2hBnAjtnCThDAL/ADU+AQAADAEBlzkQDAH/NSABAABwImpoQfNUvx1xOxovEHIiDgwJZXhjZXB0aW9uOmoTtSTxPUlyOwAHPQI9SQwBAAwC/wA12AAAAD8MAv8ANe4AAAAMAQCXORIREBPASnLKcxB0IhRqbM51DAECDAL/ADWsAAAAIgZsazDsP2hBnAjtnCSSDAL/ADW0AAAADAEClzkQDAH/NZYAAABwImxoQfNUvx1xOxpOEHJqE7VFeCYODAlleGNlcHRpb246PUtyEHNrE7UmAmsQlzk7DhMMAQMMAv8ANEdqOnQ9Aj00DAL/ADRaDAEDlzkMAQIMAv8ANCw/DAL/ADRFDAEClzkMAQMMAv8ANBc/aEGcCO2cJJAMAv8ANCgMAQOXOUA=
    /// INITSLOT 0601 [64 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 54010000 [512 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L 5B010000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 1B [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY 0005 [4 datoshi]
    /// ENDTRY 17 [4 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 30010000 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF E1 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 3E010000 [512 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L 20010000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 6A [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY 1A2F [4 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIF F1 [2 datoshi]
    /// ENDTRY 49 [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// TRY 0007 [4 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// ENDTRY 49 [4 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L D8000000 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L EE000000 [512 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC4 [2 datoshi]
    /// JMP 14 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// STLOC5 [2 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L AC000000 [512 datoshi]
    /// JMP 06 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// JMPLT EC [2 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF 92 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L B4000000 [512 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L 96000000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 6C [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY 1A4E [4 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// DROP [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// JMPIFNOT 0E [2 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// ENDTRY 4B [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIFNOT 02 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// TRY 0E13 [4 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 47 [512 datoshi]
    /// LDLOC2 [2 datoshi]
    /// THROW [512 datoshi]
    /// STLOC4 [2 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// ENDTRY 34 [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 5A [512 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 2C [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 45 [512 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 17 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF 90 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 28 [512 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("breakInTryCatch")]
    public abstract void BreakInTryCatch(bool? exception);

    #endregion
}
