using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_Syscall_Out(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Syscall_Out"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""testByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":0,""safe"":false},{""name"":""testSByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":90,""safe"":false},{""name"":""testShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":177,""safe"":false},{""name"":""testUShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":264,""safe"":false},{""name"":""testIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":359,""safe"":false},{""name"":""testUIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":452,""safe"":false},{""name"":""testLongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":554,""safe"":false},{""name"":""testULongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":647,""safe"":false},{""name"":""testBoolTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":757,""safe"":false},{""name"":""_initialize"",""parameters"":[],""returntype"":""Void"",""offset"":972,""safe"":false}],""events"":[]},""permissions"":[{""contract"":""0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0"",""methods"":[""atoi""]}],""trusts"":[],""extra"":{""Version"":""3.10.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA7znO4OTpJcbCoGp54UQN2G/OrARhdG9pAQABBQAA/c8DVwQBeHEQSmFpRnFp2CRBacpKciY7EHNpEM5KAC0oCAArKAUiCUVqESgmEXNpa84AMAA6uyYaa5xKc2ow8Wk3AABKEAEAAbsmBmAIIgZFEGAJWGFwaFlQEr9AVwQBeHEQSmNpRnFp2CQ+acpKciY4EHNpEM5KAC0oCAArKAUiCUVqESgjEXNpa84AMAA6uyYXa5xKc2ow8Wk3AABKyhEsBmIIIgZFEGIJWmNwaFtQEr9AVwQBeHEQSmVpRnFp2CQ+acpKciY4EHNpEM5KAC0oCAArKAUiCUVqESgjEXNpa84AMAA6uyYXa5xKc2ow8Wk3AABKyhIsBmQIIgZFEGQJXGVwaF1QEr9AVwQBeHEQSmcHaUZxadgkQ2nKSnImPRBzaRDOSgAtKAgAKygFIglFahEoKBFzaWvOADAAOrsmHGucSnNqMPFpNwAAShACAAABALsmBmYIIgZFEGYJXmcHcGhfB1ASv0BXBAF4cRBKZwlpRnFp2CQ/acpKciY5EHNpEM5KAC0oCAArKAUiCUVqESgkEXNpa84AMAA6uyYYa5xKc2ow8Wk3AABKyhQsB2cICCIHRRBnCAlfCGcJcGhfCVASv0BXBAF4cRBKZwtpRnFp2CRIacpKciZCEHNpEM5KAC0oCAArKAUiCUVqESgtEXNpa84AMAA6uyYha5xKc2ow8Wk3AABKEAMAAAAAAQAAALsmB2cKCCIHRRBnCglfCmcLcGhfC1ASv0BXBAF4cRBKZw1pRnFp2CQ/acpKciY5EHNpEM5KAC0oCAArKAUiCUVqESgkEXNpa84AMAA6uyYYa5xKc2ow8Wk3AABKyhgsB2cMCCIHRRBnDAlfDGcNcGhfDVASv0BXBAF4cRBKZw9pRnFp2CRQacpKciZKEHNpEM5KAC0oCAArKAUiCUVqESg1EXNpa84AMAA6uyYpa5xKc2ow8Wk3AABKEAQAAAAAAAAAAAEAAAAAAAAAuyYHZw4IIgdFEGcOCV8OZw9waF8PUBK/QFcCAXhxCUpnEWlGSgwEdHJ1ZZclrwAAAEoMBWZhbHNllyWlAAAASgwEVFJVRZcllAAAAEoMBFRydWWXJYcAAABKDAF0lyR9SgwBVJckdkoMATGXJG9KDAN5ZXOXJGZKDANZRVOXJF1KDAF5lyRWSgwBWZckT0oMBUZBTFNFlyRISgwFRmFsc2WXJD1KDAFmlyQ2SgwBRpckL0oMATCXJChKDAJub5ckIEoMAk5PlyQYSgwBbpckEUoMAU6XJAoJCSIICAgiBAgJZxBGXxBnEXBoXxFQEr9AVhJAWvRZfg==").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIBeHEJSmcRaUZKDAR0cnVllyWvAAAASgwFZmFsc2WXJaUAAABKDARUUlVFlyWUAAAASgwEVHJ1ZZclhwAAAEoMAXSXJH1KDAFUlyR2SgwBMZckb0oMA3llc5ckZkoMA1lFU5ckXUoMAXmXJFZKDAFZlyRPSgwFRkFMU0WXJEhKDAVGYWxzZZckPUoMAWaXJDZKDAFGlyQvSgwBMJckKEoMAm5vlyQgSgwCTk+XJBhKDAFulyQRSgwBTpckCgkJIggICCIECAlnEEZfEGcRcGhfEVASv0A=
    /// INITSLOT 0201 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74727565 'true' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L AF000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66616C7365 'false' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L A5000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54525545 'TRUE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 94000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54727565 'True' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 87000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74 't' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 7D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54 'T' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 76 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 6F [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 796573 'yes' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 66 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 594553 'YES' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 5D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 79 'y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 56 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 59 'Y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 4F [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46414C5345 'FALSE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 48 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46616C7365 'False' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 3D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66 'f' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 36 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46 'F' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 2F [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 28 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E6F 'no' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 20 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E4F 'NO' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 18 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E 'n' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E 'N' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0A [2 datoshi]
    /// PUSHF [1 datoshi]
    /// PUSHF [1 datoshi]
    /// JMP 08 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 04 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// PUSHF [1 datoshi]
    /// STSFLD 10 [2 datoshi]
    /// NIP [2 datoshi]
    /// LDSFLD 10 [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 11 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testBoolTryParse")]
    public abstract IList<object>? TestBoolTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmFpRnFp2CRBacpKciY7EHNpEM5KAC0oCAArKAUiCUVqESgmEXNpa84AMAA6uyYaa5xKc2ow8Wk3AABKEAEAAbsmBmAIIgZFEGAJWGFwaFlQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 41 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 26 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1A [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT16 0001 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD0 [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD1 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testByteTryParse")]
    public abstract IList<object>? TestByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcJaUZxadgkP2nKSnImORBzaRDOSgAtKAgAKygFIglFahEoJBFzaWvOADAAOrsmGGucSnNqMPFpNwAASsoULAdnCAgiB0UQZwgJXwhnCXBoXwlQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 3F [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 39 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 24 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 18 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPGT 07 [2 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 08 [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 09 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testIntTryParse")]
    public abstract IList<object>? TestIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcNaUZxadgkP2nKSnImORBzaRDOSgAtKAgAKygFIglFahEoJBFzaWvOADAAOrsmGGucSnNqMPFpNwAASsoYLAdnDAgiB0UQZwwJXwxnDXBoXw1QEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 3F [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 39 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 24 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 18 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH8 [1 datoshi]
    /// JMPGT 07 [2 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0C [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0D [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testLongTryParse")]
    public abstract IList<object>? TestLongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmNpRnFp2CQ+acpKciY4EHNpEM5KAC0oCAArKAUiCUVqESgjEXNpa84AMAA6uyYXa5xKc2ow8Wk3AABKyhEsBmIIIgZFEGIJWmNwaFtQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 3E [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 38 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 23 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 17 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPGT 06 [2 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD2 [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD3 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testSByteTryParse")]
    public abstract IList<object>? TestSByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmVpRnFp2CQ+acpKciY4EHNpEM5KAC0oCAArKAUiCUVqESgjEXNpa84AMAA6uyYXa5xKc2ow8Wk3AABKyhIsBmQIIgZFEGQJXGVwaF1QEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 3E [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 38 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 23 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 17 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH2 [1 datoshi]
    /// JMPGT 06 [2 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD4 [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD5 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testShortTryParse")]
    public abstract IList<object>? TestShortTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcLaUZxadgkSGnKSnImQhBzaRDOSgAtKAgAKygFIglFahEoLRFzaWvOADAAOrsmIWucSnNqMPFpNwAAShADAAAAAAEAAAC7JgdnCggiB0UQZwoJXwpnC3BoXwtQEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 48 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 42 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 2D [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 21 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0A [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0B [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUIntTryParse")]
    public abstract IList<object>? TestUIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcPaUZxadgkUGnKSnImShBzaRDOSgAtKAgAKygFIglFahEoNRFzaWvOADAAOrsmKWucSnNqMPFpNwAAShAEAAAAAAAAAAABAAAAAAAAALsmB2cOCCIHRRBnDglfDmcPcGhfD1ASv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 50 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 4A [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 35 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 29 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT128 00000000000000000100000000000000 [4 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0E [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 0F [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testULongTryParse")]
    public abstract IList<object>? TestULongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBeHEQSmcHaUZxadgkQ2nKSnImPRBzaRDOSgAtKAgAKygFIglFahEoKBFzaWvOADAAOrsmHGucSnNqMPFpNwAAShACAAABALsmBmYIIgZFEGYJXmcHcGhfB1ASv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// NIP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 43 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMPIFNOT 3D [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// JMPEQ 08 [2 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// JMPEQ 05 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// JMPEQ 28 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1C [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// JMPLT F1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT32 00000100 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD6 [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDSFLD 07 [2 datoshi]
    /// SWAP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUShortTryParse")]
    public abstract IList<object>? TestUShortTryParse(string? s);

    #endregion
}
