using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

namespace Neo.SmartContract.Testing;

public abstract class Contract_Continue(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Continue"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""continueInTryCatch"",""parameters"":[{""name"":""exception"",""type"":""Boolean""}],""returntype"":""Void"",""offset"":0,""safe"":false}],""events"":[]},""permissions"":[],""trusts"":[],""extra"":{""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0TAlcGAQwBAAwC/wA12gEAABAMAf814QEAAHAiG2hB81S/HXE7AAU9DwwBAQwC/wA1tgEAAD9oQZwI7Zwk4QwC/wA1xAEAAAwBAZc5EAwB/zWmAQAAcCJ3aEHzVL8dcTsaNBByIg4MCWV4Y2VwdGlvbjpqE7Uk8T1Wcgkk/zsAByIRPUsMAQAMAv8ANVsBAAA/PfEMAv8ANW8BAAAMAQCXORIREBPASnLKcxB0IhxqbM51bRK1JgQiDgwBAgwC/wA1JgEAAGycdGxrMOQ/aEGcCO2cJIUMAv8ANS0BAAAMAQKXORAMAf81DwEAAHAj4gAAAGhB81S/HXE8VwAAAMEAAAAQciIzapxKAgAAAIAuBCIKSgL///9/Mh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfcmoTtSTMeCYODAlleGNlcHRpb246PoQAAAByEHNrE7UmNmsRnkoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9zIslrE5c5Ow4TDAEDDAL/ADRMajp0Ihk9LgwC/wA0XwwBA5c5DAECDAL/ADQxPz3pDAL/ADRIDAEClzkMAQMMAv8ANBo/aEGcCO2cJR3///8MAv8ANCgMAQOXOUBXAAJ5eEGb9mfOQeY/GIRAVwACeXhB9rRr4kHfMLiaQFcAAXhB9rRr4kGSXegxQFDZU54=").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwYBDAEADAL/ADXaAQAAEAwB/zXhAQAAcCIbaEHzVL8dcTsABT0PDAEBDAL/ADW2AQAAP2hBnAjtnCThDAL/ADXEAQAADAEBlzkQDAH/NaYBAABwIndoQfNUvx1xOxo0EHIiDgwJZXhjZXB0aW9uOmoTtSTxPVZyCST/OwAHIhE9SwwBAAwC/wA1WwEAAD898QwC/wA1bwEAAAwBAJc5EhEQE8BKcspzEHQiHGpsznVtErUmBCIODAECDAL/ADUmAQAAbJx0bGsw5D9oQZwI7ZwkhQwC/wA1LQEAAAwBApc5EAwB/zUPAQAAcCPiAAAAaEHzVL8dcTxXAAAAwQAAABByIjNqnEoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9yahO1JMx4Jg4MCWV4Y2VwdGlvbjo+hAAAAHIQc2sTtSY2axGeSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3MiyWsTlzk7DhMMAQMMAv8ANExqOnQiGT0uDAL/ADRfDAEDlzkMAQIMAv8ANDE/PekMAv8ANEgMAQKXOQwBAwwC/wA0Gj9oQZwI7ZwlHf///wwC/wA0KAwBA5c5QA==
    /// INITSLOT 0601 [64 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L DA010000 [512 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L E1010000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 1B [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY 0005 [4 datoshi]
    /// ENDTRY 0F [4 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L B6010000 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF E1 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L C4010000 [512 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L A6010000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 77 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY 1A34 [4 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIF F1 [2 datoshi]
    /// ENDTRY 56 [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// JMPIF FF [2 datoshi]
    /// TRY 0007 [4 datoshi]
    /// JMP 11 [2 datoshi]
    /// ENDTRY 4B [4 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 5B010000 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// ENDTRY F1 [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 6F010000 [512 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// PACK [2048 datoshi]
    /// DUP [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC4 [2 datoshi]
    /// JMP 1C [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// STLOC5 [2 datoshi]
    /// LDLOC5 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 26010000 [512 datoshi]
    /// LDLOC4 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC4 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// JMPLT E4 [2 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF 85 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL_L 2D010000 [512 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// CALL_L 0F010000 [512 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP_L E2000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC1 [2 datoshi]
    /// TRY_L 57000000C1000000 [4 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 33 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIF CC [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// JMPIFNOT 0E [2 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// ENDTRY_L 84000000 [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// LT [8 datoshi]
    /// JMPIFNOT 36 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP C9 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// TRY 0E13 [4 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 4C [512 datoshi]
    /// LDLOC2 [2 datoshi]
    /// THROW [512 datoshi]
    /// STLOC4 [2 datoshi]
    /// JMP 19 [2 datoshi]
    /// ENDTRY 2E [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 5F [512 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 31 [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// ENDTRY E9 [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 48 [512 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 1A [512 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF_L 1DFFFFFF [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// CALL 28 [512 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("continueInTryCatch")]
    public abstract void ContinueInTryCatch(bool? exception);

    #endregion
}
