using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_Syscall_Out(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Syscall_Out"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""testByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":0,""safe"":false},{""name"":""testSByteTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":100,""safe"":false},{""name"":""testShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":201,""safe"":false},{""name"":""testUShortTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":305,""safe"":false},{""name"":""testIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":410,""safe"":false},{""name"":""testUIntTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":526,""safe"":false},{""name"":""testLongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":638,""safe"":false},{""name"":""testULongTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":766,""safe"":false},{""name"":""testBoolTryParse"",""parameters"":[{""name"":""s"",""type"":""String""}],""returntype"":""Array"",""offset"":886,""safe"":false},{""name"":""_initialize"",""parameters"":[],""returntype"":""Void"",""offset"":1108,""safe"":false}],""events"":[]},""permissions"":[{""contract"":""0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0"",""methods"":[""atoi""]}],""trusts"":[],""extra"":{""Version"":""3.9.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA7znO4OTpJcbCoGp54UQN2G/OrARhdG9pAQABDwAA/VcEVwQBEEpheFBFcWnYJE1pynJqsSZGEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkLRFza2q4JBFpa84AMAA6uyYca5xzIu5pNwAAStgkDkoQAQABuyYGYAgiBkUQYAlYYXBZaBK/QFcEARBKY3hQRXFp2CROacpyarEmRxBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJC4Rc2tquCQRaWvOADAAOrsmHWuccyLuaTcAAErYJA9KAIABgAC7JgZiCCIGRRBiCVpjcFtoEr9AVwQBEEpleFBFcWnYJFFpynJqsSZKEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkMRFza2q4JBFpa84AMAA6uyYga5xzIu5pNwAAStgkEkoBAIACAIAAALsmBmQIIgZFEGQJXGVwXWgSv0BXBAEQSmcHeFBFcWnYJE9pynJqsSZIEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkLxFza2q4JBFpa84AMAA6uyYea5xzIu5pNwAAStgkEEoQAgAAAQC7JgZmCCIGRRBmCV5nB3BfB2gSv0BXBAEQSmcJeFBFcWnYJFhpynJqsSZREHNpEM4ALbMkDGkQzgArsyQEIglqEbMkOBFza2q4JBFpa84AMAA6uyYna5xzIu5pNwAAStgkGUoCAAAAgAMAAACAAAAAALsmB2cICCIHRRBnCAlfCGcJcF8JaBK/QFcEARBKZwt4UEVxadgkVGnKcmqxJk0Qc2kQzgAtsyQMaRDOACuzJAQiCWoRsyQ0EXNrargkEWlrzgAwADq7JiNrnHMi7mk3AABK2CQVShADAAAAAAEAAAC7JgdnCggiB0UQZwoJXwpnC3BfC2gSv0BXBAEQSmcNeFBFcWnYJGRpynJqsSZdEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkRBFza2q4JBFpa84AMAA6uyYza5xzIu5pNwAAStgkJUoDAAAAAAAAAIAEAAAAAAAAAIAAAAAAAAAAALsmB2cMCCIHRRBnDAlfDGcNcF8NaBK/QFcEARBKZw94UEVxadgkXGnKcmqxJlUQc2kQzgAtsyQMaRDOACuzJAQiCWoRsyQ8EXNrargkEWlrzgAwADq7JitrnHMi7mk3AABK2CQdShAEAAAAAAAAAAABAAAAAAAAALsmB2cOCCIHRRBnDglfDmcPcF8PaBK/QFcBAQlKZxF4UEVKDAR0cnVllyW1AAAASgwEVFJVRZclqAAAAEoMBFRydWWXJZsAAABKDAF0lyWRAAAASgwBVJclhwAAAEoMATGXJH1KDAN5ZXOXJHRKDANZRVOXJGtKDAF5lyRkSgwBWZckXUoMBWZhbHNllyRZSgwFRkFMU0WXJE5KDAVGYWxzZZckQ0oMAWaXJDxKDAFGlyQ1SgwBMJckLkoMAm5vlyQmSgwCTk+XJB5KDAFulyQXSgwBTpckEEUJZxAJIg5FCGcQCCIHRQlnEAhfEGcRcF8RaBK/QFYSQC+7wOs=").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBCUpnEXhQRUoMBHRydWWXJbUAAABKDARUUlVFlyWoAAAASgwEVHJ1ZZclmwAAAEoMAXSXJZEAAABKDAFUlyWHAAAASgwBMZckfUoMA3llc5ckdEoMA1lFU5cka0oMAXmXJGRKDAFZlyRdSgwFZmFsc2WXJFlKDAVGQUxTRZckTkoMBUZhbHNllyRDSgwBZpckPEoMAUaXJDVKDAEwlyQuSgwCbm+XJCZKDAJOT5ckHkoMAW6XJBdKDAFOlyQQRQlnEAkiDkUIZxAIIgdFCWcQCF8QZxFwXxFoEr9A
    /// INITSLOT 0101 [64 datoshi]
    /// PUSHF [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74727565 'true' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L B5000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54525545 'TRUE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L A8000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54727565 'True' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 9B000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 74 't' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 91000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 54 'T' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 87000000 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 7D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 796573 'yes' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 74 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 594553 'YES' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 6B [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 79 'y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 64 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 59 'Y' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 5D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66616C7365 'false' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 59 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46414C5345 'FALSE' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 4E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46616C7365 'False' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 43 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 66 'f' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 3C [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 46 'F' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 35 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 2E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E6F 'no' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 26 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E4F 'NO' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 1E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 6E 'n' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 17 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHDATA1 4E 'N' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 10 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHF [1 datoshi]
    /// STSFLD 10 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// JMP 0E [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHT [1 datoshi]
    /// STSFLD 10 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSHF [1 datoshi]
    /// STSFLD 10 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// LDSFLD 10 [2 datoshi]
    /// STSFLD 11 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 11 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testBoolTryParse")]
    public abstract IList<object>? TestBoolTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpheFBFcWnYJE1pynJqsSZGEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkLRFza2q4JBFpa84AMAA6uyYca5xzIu5pNwAAStgkDkoQAQABuyYGYAgiBkUQYAlYYXBZaBK/QA==
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 4D [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 46 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 2D [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1C [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 0E [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT16 0001 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD0 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD0 [2 datoshi]
    /// STSFLD1 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD1 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testByteTryParse")]
    public abstract IList<object>? TestByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpnCXhQRXFp2CRYacpyarEmURBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJDgRc2tquCQRaWvOADAAOrsmJ2uccyLuaTcAAErYJBlKAgAAAIADAAAAgAAAAAC7JgdnCAgiB0UQZwgJXwhnCXBfCWgSv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 58 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 51 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 38 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 27 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 19 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// PUSHINT64 0000008000000000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 08 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 08 [2 datoshi]
    /// STSFLD 09 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 09 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testIntTryParse")]
    public abstract IList<object>? TestIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpnDXhQRXFp2CRkacpyarEmXRBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJEQRc2tquCQRaWvOADAAOrsmM2uccyLuaTcAAErYJCVKAwAAAAAAAACABAAAAAAAAACAAAAAAAAAAAC7JgdnDAgiB0UQZwwJXwxnDXBfDWgSv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 64 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 5D [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 44 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 33 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 25 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT64 0000000000000080 [1 datoshi]
    /// PUSHINT128 00000000000000800000000000000000 [4 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0C [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0C [2 datoshi]
    /// STSFLD 0D [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 0D [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testLongTryParse")]
    public abstract IList<object>? TestLongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpjeFBFcWnYJE5pynJqsSZHEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkLhFza2q4JBFpa84AMAA6uyYda5xzIu5pNwAAStgkD0oAgAGAALsmBmIIIgZFEGIJWmNwW2gSv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 4E [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 47 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 2E [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1D [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 0F [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT8 80 [1 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD2 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD2 [2 datoshi]
    /// STSFLD3 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD3 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testSByteTryParse")]
    public abstract IList<object>? TestSByteTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpleFBFcWnYJFFpynJqsSZKEHNpEM4ALbMkDGkQzgArsyQEIglqEbMkMRFza2q4JBFpa84AMAA6uyYga5xzIu5pNwAAStgkEkoBAIACAIAAALsmBmQIIgZFEGQJXGVwXWgSv0A=
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 51 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 4A [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 31 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 20 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 12 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT16 0080 [1 datoshi]
    /// PUSHINT32 00800000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD4 [2 datoshi]
    /// STSFLD5 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD5 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testShortTryParse")]
    public abstract IList<object>? TestShortTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpnC3hQRXFp2CRUacpyarEmTRBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJDQRc2tquCQRaWvOADAAOrsmI2uccyLuaTcAAErYJBVKEAMAAAAAAQAAALsmB2cKCCIHRRBnCglfCmcLcF8LaBK/QA==
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 54 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 4D [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 34 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 23 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 15 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0A [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0A [2 datoshi]
    /// STSFLD 0B [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 0B [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUIntTryParse")]
    public abstract IList<object>? TestUIntTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpnD3hQRXFp2CRcacpyarEmVRBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJDwRc2tquCQRaWvOADAAOrsmK2uccyLuaTcAAErYJB1KEAQAAAAAAAAAAAEAAAAAAAAAuyYHZw4IIgdFEGcOCV8OZw9wXw9oEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 5C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 55 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 3C [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 2B [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 1D [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT128 00000000000000000100000000000000 [4 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 07 [2 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 07 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD 0E [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD 0E [2 datoshi]
    /// STSFLD 0F [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 0F [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testULongTryParse")]
    public abstract IList<object>? TestULongTryParse(string? s);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwQBEEpnB3hQRXFp2CRPacpyarEmSBBzaRDOAC2zJAxpEM4AK7MkBCIJahGzJC8Rc2tquCQRaWvOADAAOrsmHmuccyLuaTcAAErYJBBKEAIAAAEAuyYGZggiBkUQZgleZwdwXwdoEr9A
    /// INITSLOT 0401 [64 datoshi]
    /// PUSH0 [1 datoshi]
    /// DUP [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// SWAP [2 datoshi]
    /// DROP [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 4F [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// NZ [4 datoshi]
    /// JMPIFNOT 48 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2D [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 2B [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 09 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NUMEQUAL [8 datoshi]
    /// JMPIF 2F [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// GE [8 datoshi]
    /// JMPIF 11 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// PUSHINT8 30 [1 datoshi]
    /// PUSHINT8 3A [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 1E [2 datoshi]
    /// LDLOC3 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC3 [2 datoshi]
    /// JMP EE [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 10 [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHINT32 00000100 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIFNOT 06 [2 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// JMP 06 [2 datoshi]
    /// DROP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STSFLD6 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// LDSFLD6 [2 datoshi]
    /// STSFLD 07 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDSFLD 07 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PACKSTRUCT [2048 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testUShortTryParse")]
    public abstract IList<object>? TestUShortTryParse(string? s);

    #endregion
}
