using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_IndexOrRange(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_IndexOrRange"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""testMain"",""parameters"":[],""returntype"":""Void"",""offset"":0,""safe"":false},{""name"":""testFromEndRangeEvaluationOrder"",""parameters"":[],""returntype"":""Integer"",""offset"":1130,""safe"":false},{""name"":""testStringRangeEvaluationOrder"",""parameters"":[],""returntype"":""String"",""offset"":1175,""safe"":false},{""name"":""testNullLeftFromEndRangeEvaluationOrder"",""parameters"":[],""returntype"":""Void"",""offset"":1219,""safe"":false},{""name"":""testNullRightFromEndRangeEvaluationOrder"",""parameters"":[],""returntype"":""Void"",""offset"":1274,""safe"":false},{""name"":""testConditionalNullRangeSkipsEndpoints"",""parameters"":[],""returntype"":""Boolean"",""offset"":1329,""safe"":false},{""name"":""testNegativeStartSkipsEndEvaluation"",""parameters"":[],""returntype"":""Void"",""offset"":1388,""safe"":false},{""name"":""testNegativeFromEndStopsAfterEndEvaluation"",""parameters"":[],""returntype"":""Void"",""offset"":1440,""safe"":false}],""events"":[]},""permissions"":[{""contract"":""0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0"",""methods"":[""itoa""]}],""trusts"":[],""extra"":{""Version"":""3.10.1"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA7znO4OTpJcbCoGp54UQN2G/OrARpdG9hAQABBQAA/dYFVxYANQUEAAA1GQQAAEoQLgM6NR0EAABKEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4xwaMo3AABBz+dHlgwKAQIDBAUGBwgJChqNcWkQS8pKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+McmkQE0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHNpEkoQLgM6S8pKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdGkTShAuAzoVShAuAzpKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdWkSShAuAzqcm0vKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHZpEBNKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHcHaRNKEC4DOhRKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHcIaRRKEC4DOpybEkoQLgM6nJtKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdwlpEM53CmrKNwAAQc/nR5ZryjcAAEHP50eWbMo3AABBz+dHlm3KNwAAQc/nR5ZuyjcAAEHP50eWbwfKNwAAQc/nR5ZvCMo3AABBz+dHlm8JyjcAAEHP50eWbwo3AABBz+dHlgwJMTIzNDU2Nzg5dwtvCxBLykoQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcMbwsQE0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodw1vCxJKEC4DOkvKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodw5vCxNKEC4DOhVKEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcPbwsSShAuAzqcm0vKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodxBvCxATShAuAzqcm0oQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcRbwsTShAuAzoUShAuAzqcm0oQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcSbwsUShAuAzqcmxJKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodxNvCxDOdxRvDNsoQc/nR5ZvDdsoQc/nR5ZvDtsoQc/nR5ZvD9soQc/nR5ZvENsoQc/nR5ZvEdsoQc/nR5ZvEtsoQc/nR5ZvE9soQc/nR5ZvFHcVbxUQKHJvFQB/MmhvFQH/BzJDbxUCANgAAAIA4AAAuyQtE4hKEG8VHKkfkQHgAJLQShFvFRapAD+RAYAAktBKEm8VAD+RAYAAktAiNQwD77+9Ii4SiEoQbxUWqQAfkQHAAJLQShFvFQA/kQGAAJLQIhBvFSIMEYhKEG8VAH+R0NsoQc/nR5ZADAhyZWNlaXZlckHP50eWDAUBAgMEBRWNQAwFc3RhcnRBz+dHlhFADANlbmRBz+dHlhRADA9zdHJpbmcgcmVjZWl2ZXJBz+dHlgwFMTIzNDVADAhuZWdhdGl2ZUHP50eWD0A0njS1ShAuAzqcmzS6ShAuAzpKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MykA0pDSIShAuAzo0j0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsoQFcBAAtwaDVY////ShAuAzqcmzVa////ShAuAzpKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MRUBXAQALcGg1If///0oQLgM6NSX///9KEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjEVAVwIAC3BoStgkLzXm/v//ShAuAzo16v7//0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHFp2EA1nP7//zXo/v//ShAuAzo1tP7//0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjEVANWj+//81fP7//0oQLgM6Nar+//9KEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjEVAOJPMVg==").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIAC3BoStgkLzXm/v//ShAuAzo16v7//0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHFp2EA=
    /// INITSLOT 0200 [64 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// DUP [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 2F [2 datoshi]
    /// CALL_L E6FEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL_L EAFEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testConditionalNullRangeSkipsEndpoints")]
    public abstract bool? TestConditionalNullRangeSkipsEndpoints();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: NJ40tUoQLgM6nJs0ukoQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjMpA
    /// CALL 9E [512 datoshi]
    /// CALL B5 [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// CALL BA [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// SIZE [4 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testFromEndRangeEvaluationOrder")]
    public abstract BigInteger? TestFromEndRangeEvaluationOrder();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VxYANQUEAAA1GQQAAEoQLgM6NR0EAABKEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4xwaMo3AABBz+dHlgwKAQIDBAUGBwgJChqNcWkQS8pKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+McmkQE0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHNpEkoQLgM6S8pKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdGkTShAuAzoVShAuAzpKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdWkSShAuAzqcm0vKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHZpEBNKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHcHaRNKEC4DOhRKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjHcIaRRKEC4DOpybEkoQLgM6nJtKEC4IEk3KUJ6cUEoQLggSTcpQnpxQS5+MdwlpEM53CmrKNwAAQc/nR5ZryjcAAEHP50eWbMo3AABBz+dHlm3KNwAAQc/nR5ZuyjcAAEHP50eWbwfKNwAAQc/nR5ZvCMo3AABBz+dHlm8JyjcAAEHP50eWbwo3AABBz+dHlgwJMTIzNDU2Nzg5dwtvCxBLykoQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcMbwsQE0oQLgM6ShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodw1vCxJKEC4DOkvKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodw5vCxNKEC4DOhVKEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcPbwsSShAuAzqcm0vKShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodxBvCxATShAuAzqcm0oQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcRbwsTShAuAzoUShAuAzqcm0oQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKHcSbwsUShAuAzqcmxJKEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjNsodxNvCxDOdxRvDNsoQc/nR5ZvDdsoQc/nR5ZvDtsoQc/nR5ZvD9soQc/nR5ZvENsoQc/nR5ZvEdsoQc/nR5ZvEtsoQc/nR5ZvE9soQc/nR5ZvFHcVbxUQKHJvFQB/MmhvFQH/BzJDbxUCANgAAAIA4AAAuyQtE4hKEG8VHKkfkQHgAJLQShFvFRapAD+RAYAAktBKEm8VAD+RAYAAktAiNQwD77+9Ii4SiEoQbxUWqQAfkQHAAJLQShFvFQA/kQGAAJLQIhBvFSIMEYhKEG8VAH+R0NsoQc/nR5ZA
    /// INITSLOT 1600 [64 datoshi]
    /// CALL_L 05040000 [512 datoshi]
    /// CALL_L 19040000 [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL_L 1D040000 [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// PUSHDATA1 0102030405060708090A [8 datoshi]
    /// PUSH10 [1 datoshi]
    /// LEFT [2048 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC2 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC3 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC4 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// PUSH5 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC5 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC6 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC 07 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// PUSH4 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC 08 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH4 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// STLOC 09 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// STLOC 0A [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC3 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC4 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC5 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC6 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 09 [2 datoshi]
    /// SIZE [4 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 0A [2 datoshi]
    /// CALLT 0000 [32768 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// PUSHDATA1 313233343536373839 '123456789' [8 datoshi]
    /// STLOC 0B [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 0C [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 0D [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 0E [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// PUSH5 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 0F [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// OVER [2 datoshi]
    /// SIZE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 10 [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 11 [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// PUSH4 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 12 [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH4 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// PUSH2 [1 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// STLOC 13 [2 datoshi]
    /// LDLOC 0B [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PICKITEM [64 datoshi]
    /// STLOC 14 [2 datoshi]
    /// LDLOC 0C [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 0D [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 0E [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 0F [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 10 [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 11 [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 12 [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 13 [2 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// LDLOC 14 [2 datoshi]
    /// STLOC 15 [2 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPEQ 72 [2 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT8 7F [1 datoshi]
    /// JMPLE 68 [2 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT16 FF07 [1 datoshi]
    /// JMPLE 43 [2 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT32 00D80000 [1 datoshi]
    /// PUSHINT32 00E00000 [1 datoshi]
    /// WITHIN [8 datoshi]
    /// JMPIF 2D [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// NEWBUFFER [256 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSH12 [1 datoshi]
    /// SHR [8 datoshi]
    /// PUSH15 [1 datoshi]
    /// AND [8 datoshi]
    /// PUSHINT16 E000 [1 datoshi]
    /// OR [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSH6 [1 datoshi]
    /// SHR [8 datoshi]
    /// PUSHINT8 3F [1 datoshi]
    /// AND [8 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// OR [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// DUP [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT8 3F [1 datoshi]
    /// AND [8 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// OR [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// JMP 35 [2 datoshi]
    /// PUSHDATA1 EFBFBD '???' [8 datoshi]
    /// JMP 2E [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// NEWBUFFER [256 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSH6 [1 datoshi]
    /// SHR [8 datoshi]
    /// PUSHINT8 1F [1 datoshi]
    /// AND [8 datoshi]
    /// PUSHINT16 C000 [1 datoshi]
    /// OR [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// DUP [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT8 3F [1 datoshi]
    /// AND [8 datoshi]
    /// PUSHINT16 8000 [1 datoshi]
    /// OR [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// JMP 10 [2 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// JMP 0C [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// NEWBUFFER [256 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// LDLOC 15 [2 datoshi]
    /// PUSHINT8 7F [1 datoshi]
    /// AND [8 datoshi]
    /// SETITEM [8192 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// SYSCALL CFE74796 'System.Runtime.Log' [32768 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testMain")]
    public abstract void TestMain();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: NWj+//81fP7//0oQLgM6Nar+//9KEC4DOpybShAuCBJNylCenFBKEC4IEk3KUJ6cUEufjEVA
    /// CALL_L 68FEFFFF [512 datoshi]
    /// CALL_L 7CFEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL_L AAFEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// DROP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testNegativeFromEndStopsAfterEndEvaluation")]
    public abstract void TestNegativeFromEndStopsAfterEndEvaluation();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: NZz+//816P7//0oQLgM6NbT+//9KEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4xFQA==
    /// CALL_L 9CFEFFFF [512 datoshi]
    /// CALL_L E8FEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL_L B4FEFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// DROP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testNegativeStartSkipsEndEvaluation")]
    public abstract void TestNegativeStartSkipsEndEvaluation();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEAC3BoNVj///9KEC4DOpybNVr///9KEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4xFQA==
    /// INITSLOT 0100 [64 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// CALL_L 58FFFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// CALL_L 5AFFFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// DROP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testNullLeftFromEndRangeEvaluationOrder")]
    public abstract void TestNullLeftFromEndRangeEvaluationOrder();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEAC3BoNSH///9KEC4DOjUl////ShAuAzqcm0oQLggSTcpQnpxQShAuCBJNylCenFBLn4xFQA==
    /// INITSLOT 0100 [64 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// CALL_L 21FFFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL_L 25FFFFFF [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// INC [4 datoshi]
    /// NEGATE [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// DROP [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testNullRightFromEndRangeEvaluationOrder")]
    public abstract void TestNullRightFromEndRangeEvaluationOrder();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: NKQ0iEoQLgM6NI9KEC4DOkoQLggSTcpQnpxQShAuCBJNylCenFBLn4zbKEA=
    /// CALL A4 [512 datoshi]
    /// CALL 88 [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// CALL 8F [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 03 [2 datoshi]
    /// THROW [512 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// JMPGE 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// PICK [2 datoshi]
    /// SIZE [4 datoshi]
    /// SWAP [2 datoshi]
    /// ADD [8 datoshi]
    /// INC [4 datoshi]
    /// SWAP [2 datoshi]
    /// OVER [2 datoshi]
    /// SUB [8 datoshi]
    /// SUBSTR [2048 datoshi]
    /// CONVERT 28 'ByteString' [8192 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testStringRangeEvaluationOrder")]
    public abstract string? TestStringRangeEvaluationOrder();

    #endregion
}
