using Neo.Cryptography.ECC;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

namespace Neo.SmartContract.Testing;

public abstract class Contract_Switch(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_Switch"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""switchLong"",""parameters"":[{""name"":""method"",""type"":""String""}],""returntype"":""Any"",""offset"":0,""safe"":false},{""name"":""switch6"",""parameters"":[{""name"":""method"",""type"":""String""}],""returntype"":""Any"",""offset"":233,""safe"":false},{""name"":""switch6Inline"",""parameters"":[{""name"":""method"",""type"":""String""}],""returntype"":""Any"",""offset"":297,""safe"":false},{""name"":""switchInteger"",""parameters"":[{""name"":""b"",""type"":""Integer""}],""returntype"":""Any"",""offset"":364,""safe"":false},{""name"":""switchLongLong"",""parameters"":[{""name"":""test"",""type"":""String""}],""returntype"":""Any"",""offset"":404,""safe"":false}],""events"":[]},""permissions"":[],""trusts"":[],""extra"":{""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Neo.IO.Helper.AsSerializable<Neo.SmartContract.NefFile>(Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP1gA1cBAXhwaAwBMJclrQAAAGgMATGXJaUAAABoDAEylyWdAAAAaAwBM5cllQAAAGgMATSXJY0AAABoDAE1lyWFAAAAaAwBNpckfWgMATeXJHhoDAE4lyRzaAwBOZckbmgMAjEwlyRoaAwCMTGXJGJoDAIxMpckXGgMAjEzlyRWaAwCMTSXJFBoDAIxNZckSmgMAjE2lyREaAwCMTeXJD9oDAIxOJckOmgMAjE5lyQ1aAwCMjCXJDAiMRFAEkATQBRAFUAWQBdAGEAZQBpAG0AcQB1AHkAfQCBAABFAABJAABNAABRAABVAAGNAVwEBeHBoDAEwlyQnaAwBMZckImgMATKXJB1oDAEzlyQYaAwBNJckE2gMATWXJA4iDhFAEkATQBRAFUAWQABjQFcBAXhwaAwBMJcmBBFAaAwBMZcmBBJAaAwBMpcmBBNAaAwBM5cmBBRAaAwBNJcmBBVAaAwBNZcmBBZACCYFAGNAaDpXAgERcHhxaRGXJA5pEpckDWkTlyQMIg4ScCIME3AiCBZwIgQQcGhAVwIBEXB4cWkMAWGXJEBpDAFjlyRxaQwBYpcloQAAAGkMAWSXJc8AAABpDAFllyX8AAAAaQwBZpclJgEAAGkMAWeXJVABAAAjfwEAAGhKnEoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRSNLAQAAaBKgSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AjFAEAAGhKnUoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRSPcAAAAaA+gSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AjpQAAAGhooEoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wIm5oE6BKAgAAAIAuBCIKSgL///9/Mh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfcCI6aBKeSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AiBmgRoXBoQH2/0+M="));

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBeHBoDAEwlyQnaAwBMZckImgMATKXJB1oDAEzlyQYaAwBNJckE2gMATWXJA4iDhFAEkATQBRAFUAWQABjQA==
    /// INITSLOT 0101 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 27 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 22 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 32 '2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 1D [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 33 '3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 18 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 34 '4' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 13 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 35 '5' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0E [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH4 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH5 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH6 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 63 [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("switch6")]
    public abstract object? Switch6(string? method);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBeHBoDAEwlyYEEUBoDAExlyYEEkBoDAEylyYEE0BoDAEzlyYEFEBoDAE0lyYEFUBoDAE1lyYEFkAIJgUAY0BoOg==
    /// INITSLOT 0101 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 32 '2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 33 '3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH4 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 34 '4' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH5 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 35 '5' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 04 [2 datoshi]
    /// PUSH6 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHT [1 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// PUSHINT8 63 [1 datoshi]
    /// RET [0 datoshi]
    /// LDLOC0 [2 datoshi]
    /// THROW [512 datoshi]
    /// </remarks>
    [DisplayName("switch6Inline")]
    public abstract object? Switch6Inline(string? method);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIBEXB4cWkRlyQOaRKXJA1pE5ckDCIOEnAiDBNwIggWcCIEEHBoQA==
    /// INITSLOT 0201 [64 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0E [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0D [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 0C [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 08 [2 datoshi]
    /// PUSH6 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 04 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("switchInteger")]
    public abstract object? SwitchInteger(BigInteger? b);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEBeHBoDAEwlyWtAAAAaAwBMZclpQAAAGgMATKXJZ0AAABoDAEzlyWVAAAAaAwBNJcljQAAAGgMATWXJYUAAABoDAE2lyR9aAwBN5ckeGgMATiXJHNoDAE5lyRuaAwCMTCXJGhoDAIxMZckYmgMAjEylyRcaAwCMTOXJFZoDAIxNJckUGgMAjE1lyRKaAwCMTaXJERoDAIxN5ckP2gMAjE4lyQ6aAwCMTmXJDVoDAIyMJckMCIxEUASQBNAFEAVQBZAF0AYQBlAGkAbQBxAHUAeQB9AIEAAEUAAEkAAE0AAFEAAFUAAY0A=
    /// INITSLOT 0101 [64 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 30 '0' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L AD000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 31 '1' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L A5000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 32 '2' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 9D000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 33 '3' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 95000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 34 '4' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 8D000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 35 '5' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 85000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 36 '6' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 7D [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 37 '7' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 78 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 38 '8' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 73 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 39 '9' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 6E [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3130 '10' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 68 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3131 '11' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 62 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3132 '12' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 5C [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3133 '13' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 56 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3134 '14' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 50 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3135 '15' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 4A [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3136 '16' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 44 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3137 '17' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 3F [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3138 '18' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 3A [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3139 '19' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 35 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHDATA1 3230 '20' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 30 [2 datoshi]
    /// JMP 31 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH2 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH3 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH4 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH5 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH6 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH7 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH8 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH9 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH10 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH11 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH12 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH13 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH14 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH15 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSH16 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 11 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 12 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 13 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 14 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 15 [1 datoshi]
    /// RET [0 datoshi]
    /// PUSHINT8 63 [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("switchLong")]
    public abstract object? SwitchLong(string? method);

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIBEXB4cWkMAWGXJEBpDAFjlyRxaQwBYpcloQAAAGkMAWSXJc8AAABpDAFllyX8AAAAaQwBZpclJgEAAGkMAWeXJVABAAAjfwEAAGhKnEoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRSNLAQAAaBKgSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AjFAEAAGhKnUoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRSPcAAAAaA+gSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AjpQAAAGhooEoCAAAAgC4EIgpKAv///38yHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wIm5oE6BKAgAAAIAuBCIKSgL///9/Mh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfcCI6aBKeSgIAAACALgQiCkoC////fzIeA/////8AAAAAkUoC////fzIMAwAAAAABAAAAn3AiBmgRoXBoQA==
    /// INITSLOT 0201 [64 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 61 'a' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 40 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 63 'c' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 71 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 62 'b' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L A1000000 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 64 'd' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L CF000000 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 65 'e' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L FC000000 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 66 'f' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 26010000 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// PUSHDATA1 67 'g' [8 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF_L 50010000 [2 datoshi]
    /// JMP_L 7F010000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// DUP [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// DROP [2 datoshi]
    /// JMP_L 4B010000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// MUL [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP_L 14010000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// DUP [2 datoshi]
    /// DEC [4 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// DROP [2 datoshi]
    /// JMP_L DC000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHM1 [1 datoshi]
    /// MUL [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP_L A5000000 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// MUL [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 6E [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// MUL [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 3A [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// ADD [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 00000080 [1 datoshi]
    /// JMPGE 04 [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 06 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// DIV [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("switchLongLong")]
    public abstract object? SwitchLongLong(string? test);

    #endregion
}
