using Neo.Cryptography.ECC;
using Neo.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;

#pragma warning disable CS0067

namespace Neo.SmartContract.Testing;

public abstract class Contract_GoTo(Neo.SmartContract.Testing.SmartContractInitialize initialize) : Neo.SmartContract.Testing.SmartContract(initialize), IContractInfo
{
    #region Compiled data

    public static Neo.SmartContract.Manifest.ContractManifest Manifest => Neo.SmartContract.Manifest.ContractManifest.Parse(@"{""name"":""Contract_GoTo"",""groups"":[],""features"":{},""supportedstandards"":[],""abi"":{""methods"":[{""name"":""test"",""parameters"":[],""returntype"":""Integer"",""offset"":0,""safe"":false},{""name"":""testTry"",""parameters"":[],""returntype"":""Integer"",""offset"":50,""safe"":false},{""name"":""testTryComplex"",""parameters"":[{""name"":""exception"",""type"":""Boolean""}],""returntype"":""Void"",""offset"":112,""safe"":false}],""events"":[]},""permissions"":[],""trusts"":[],""extra"":{""Version"":""3.10.0"",""nef"":{""optimization"":""All""}}}");

    /// <summary>
    /// Optimization: "All"
    /// </summary>
    public static Neo.SmartContract.NefFile Nef => Convert.FromBase64String(@"TkVGM1Rlc3RpbmdFbmdpbmUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0yAlcBABFwaEqcSsoUMh4D/////wAAAACRSgL///9/MgwDAAAAAAEAAACfcEVoE5cm12hAVwIAEXA7MwBoSpxKyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRWgTlyYFaD0JPQVxPQIiykBXCQEMAQAMAv8AQTkM4woIcBAMAf9BB3ZS83FpciJbakHzVL8dczsAK2h0bAiXJAts2CQHbAmXJBg7AAc9Aj3TDAL/AEHVjV7oDAEAlzk/PTFodGwIlyQNbNgkDWwJlyQMIgoLcCISCXAiDgwBAQwC/wBBOQzjCj9qQZwI7ZwkoWgJlzkMAv8AQdWNXugMAQGXORAMAf9BB3ZS83IiempB81S/HXM7DyQMCWV4Y2VwdGlvbjp0OwAHPQI9ZAwBAAwC/wBBOQzjCj8MAv8AQdWNXugMAQCXORIREA8UwEp0ynUQdiIubG7OdwdvB3cIbwgQlyQcbwgRlyQWbwgSlyQEIg4MAQIMAv8AQTkM4wpunHZubTDSP2pBnAjtnCSCDAL/AEHVjV7oDAEClzkQDAH/QQd2UvNyInVqQfNUvx1zOx9ReHRsCZckFWwIlyQEPV0MCWV4Y2VwdGlvbjo9T3Q7ERYMAQMMAv8AQTkM4wpsOnU9Aj1ADAL/AEHVjV7oDAEDlzkMAQIMAv8AQTkM4wo/DAL/AEHVjV7oDAEClzkMAQMMAv8AQTkM4wo/akGcCO2cJIcMAv8AQdWNXugMAQOXOUC0Al+F").AsSerializable<Neo.SmartContract.NefFile>();

    #endregion

    #region Unsafe methods

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwEAEXBoSpxKyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRWgTlybXaEA=
    /// INITSLOT 0100 [64 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// DUP [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT D7 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("test")]
    public abstract BigInteger? Test();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwIAEXA7MwBoSpxKyhQyHgP/////AAAAAJFKAv///38yDAMAAAAAAQAAAJ9wRWgTlyYFaD0JPQVxPQIiykA=
    /// INITSLOT 0200 [64 datoshi]
    /// PUSH1 [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// TRY 3300 [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// DUP [2 datoshi]
    /// INC [4 datoshi]
    /// DUP [2 datoshi]
    /// SIZE [4 datoshi]
    /// PUSH4 [1 datoshi]
    /// JMPLE 1E [2 datoshi]
    /// PUSHINT64 FFFFFFFF00000000 [1 datoshi]
    /// AND [8 datoshi]
    /// DUP [2 datoshi]
    /// PUSHINT32 FFFFFF7F [1 datoshi]
    /// JMPLE 0C [2 datoshi]
    /// PUSHINT64 0000000001000000 [1 datoshi]
    /// SUB [8 datoshi]
    /// STLOC0 [2 datoshi]
    /// DROP [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSH3 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIFNOT 05 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// ENDTRY 09 [4 datoshi]
    /// ENDTRY 05 [4 datoshi]
    /// STLOC1 [2 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// JMP CA [2 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testTry")]
    public abstract BigInteger? TestTry();

    /// <summary>
    /// Unsafe method
    /// </summary>
    /// <remarks>
    /// Script: VwkBDAEADAL/AEE5DOMKCHAQDAH/QQd2UvNxaXIiW2pB81S/HXM7ACtodGwIlyQLbNgkB2wJlyQYOwAHPQI90wwC/wBB1Y1e6AwBAJc5Pz0xaHRsCJckDWzYJA1sCZckDCIKC3AiEglwIg4MAQEMAv8AQTkM4wo/akGcCO2cJKFoCZc5DAL/AEHVjV7oDAEBlzkQDAH/QQd2UvNyInpqQfNUvx1zOw8kDAlleGNlcHRpb246dDsABz0CPWQMAQAMAv8AQTkM4wo/DAL/AEHVjV7oDAEAlzkSERAPFMBKdMp1EHYiLmxuzncHbwd3CG8IEJckHG8IEZckFm8IEpckBCIODAECDAL/AEE5DOMKbpx2bm0w0j9qQZwI7ZwkggwC/wBB1Y1e6AwBApc5EAwB/0EHdlLzciJ1akHzVL8dczsfUXh0bAmXJBVsCJckBD1dDAlleGNlcHRpb246PU90OxEWDAEDDAL/AEE5DOMKbDp1PQI9QAwC/wBB1Y1e6AwBA5c5DAECDAL/AEE5DOMKPwwC/wBB1Y1e6AwBApc5DAEDDAL/AEE5DOMKP2pBnAjtnCSHDAL/AEHVjV7oDAEDlzlA
    /// INITSLOT 0901 [64 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// PUSHT [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// SYSCALL 077652F3 'System.Storage.Local.Find' [32768 datoshi]
    /// STLOC1 [2 datoshi]
    /// LDLOC1 [2 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 5B [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC3 [2 datoshi]
    /// TRY 002B [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// STLOC4 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0B [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 07 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 18 [2 datoshi]
    /// TRY 0007 [4 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// ENDTRY D3 [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// ENDTRY 31 [4 datoshi]
    /// LDLOC0 [2 datoshi]
    /// STLOC4 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0D [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// ISNULL [2 datoshi]
    /// JMPIF 0D [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 0C [2 datoshi]
    /// JMP 0A [2 datoshi]
    /// PUSHNULL [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 12 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// STLOC0 [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF A1 [2 datoshi]
    /// LDLOC0 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 01 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// SYSCALL 077652F3 'System.Storage.Local.Find' [32768 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 7A [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC3 [2 datoshi]
    /// TRY 0F24 [4 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// STLOC4 [2 datoshi]
    /// TRY 0007 [4 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// ENDTRY 64 [4 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 00 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH2 [1 datoshi]
    /// PUSH1 [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHM1 [1 datoshi]
    /// PUSH4 [1 datoshi]
    /// PACK [2048 datoshi]
    /// DUP [2 datoshi]
    /// STLOC4 [2 datoshi]
    /// SIZE [4 datoshi]
    /// STLOC5 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// STLOC6 [2 datoshi]
    /// JMP 2E [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// PICKITEM [64 datoshi]
    /// STLOC 07 [2 datoshi]
    /// LDLOC 07 [2 datoshi]
    /// STLOC 08 [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// PUSH0 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 1C [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// PUSH1 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 16 [2 datoshi]
    /// LDLOC 08 [2 datoshi]
    /// PUSH2 [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// JMP 0E [2 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// LDLOC6 [2 datoshi]
    /// INC [4 datoshi]
    /// STLOC6 [2 datoshi]
    /// LDLOC6 [2 datoshi]
    /// LDLOC5 [2 datoshi]
    /// JMPLT D2 [2 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF 82 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSH0 [1 datoshi]
    /// PUSHDATA1 FF '?' [8 datoshi]
    /// SYSCALL 077652F3 'System.Storage.Local.Find' [32768 datoshi]
    /// STLOC2 [2 datoshi]
    /// JMP 75 [2 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL F354BF1D 'System.Iterator.Value' [16 datoshi]
    /// STLOC3 [2 datoshi]
    /// TRY 1F51 [4 datoshi]
    /// LDARG0 [2 datoshi]
    /// STLOC4 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHF [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 15 [2 datoshi]
    /// LDLOC4 [2 datoshi]
    /// PUSHT [1 datoshi]
    /// EQUAL [32 datoshi]
    /// JMPIF 04 [2 datoshi]
    /// ENDTRY 5D [4 datoshi]
    /// PUSHDATA1 657863657074696F6E 'exception' [8 datoshi]
    /// THROW [512 datoshi]
    /// ENDTRY 4F [4 datoshi]
    /// STLOC4 [2 datoshi]
    /// TRY 1116 [4 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// LDLOC4 [2 datoshi]
    /// THROW [512 datoshi]
    /// STLOC5 [2 datoshi]
    /// ENDTRY 02 [4 datoshi]
    /// ENDTRY 40 [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 02 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL 390CE30A 'System.Storage.Local.Put' [32768 datoshi]
    /// ENDFINALLY [4 datoshi]
    /// LDLOC2 [2 datoshi]
    /// SYSCALL 9C08ED9C 'System.Iterator.Next' [32768 datoshi]
    /// JMPIF 87 [2 datoshi]
    /// PUSHDATA1 FF00 [8 datoshi]
    /// SYSCALL D58D5EE8 'System.Storage.Local.Get' [32768 datoshi]
    /// PUSHDATA1 03 [8 datoshi]
    /// EQUAL [32 datoshi]
    /// ASSERT [1 datoshi]
    /// RET [0 datoshi]
    /// </remarks>
    [DisplayName("testTryComplex")]
    public abstract void TestTryComplex(bool? exception);

    #endregion
}
